mmcv/runner/hooks/logger/text.py
Add eta to text log. Here is output from mmdet:
``2018-12-08 07:17:36,804 - INFO - Epoch [3][100/7330]    lr: 0.02000, eta: 9:45:12, time: 0.473, data_time: 0.007, loss_rpn_cls: 0.0338, loss_rpn_reg: 0.0327, loss_cls: 0.2254, acc: 92.6582, loss_reg: 0.1204, loss: 0.4123``
p/s: Not sure ``time`` is already included ``data_time`` or not.
=> add eta to log

mmcv/cnn/__init__.py, mmcv/cnn/weight_init.py
The implementations of caffe2 and pytorch are different. `XavierFill` in Caffe2 corresponds to `kaiming_uniform_` in PyTorch.
=> Add caffe2_xavier_init()

mmcv/utils/config.py, mmcv/utils/misc.py, mmcv/utils/progressbar.py
ABCs imported from `collections` will be deprecated in python 3.8+, while `collections.abc` is not available in python 2.7
=> Use collections.abc instead of collections

setup.py
When install on windows, there is a potential bug:
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 501: illegal multibyte sequence
```
Fix according to [https://github.com/JuliaPy/pyjulia/pull/219/files](https://github.com/JuliaPy/pyjulia/pull/219/files)
=> fix possible encoding error when install

mmcv/runner/runner.py, tests/test_runner.py
As for now the latest checkpoint is a symlink with a full path in it:
```
-rw-r--r-- 1 nizhib nizhib 683M Jun  7 15:33 epoch_80.pth
-rw-r--r-- 1 nizhib nizhib 683M Jun  7 15:40 epoch_90.pth
lrwxrwxrwx 1 nizhib nizhib   90 Jun  7 15:46 latest.pth -> /home/nizhib/Code/japan/output/detector/cascade_rcnn_dconv_c3-c5_r101_fpn_1x/epoch_100.pth
```
The request applied makes it relative:
```
-rw-r--r-- 1 nizhib nizhib 683M Jun  7 15:33 epoch_80.pth
-rw-r--r-- 1 nizhib nizhib 683M Jun  7 15:40 epoch_90.pth
lrwxrwxrwx 1 nizhib nizhib   13 Jun  9 13:20 latest.pth -> epoch_100.pth
```
Resolves #74.
=> Make latest checkpoint symlink relative

mmcv/video/optflow_warp/flow_warp.cpp, mmcv/video/optflow_warp/flow_warp.hpp
`__max` and `__min` had been define as macro in visual studio compile tools.
Renaming to `__max__` and `__min__` to fix the build-errors.
=> Fixing build-errors on Windows

mmcv/runner/checkpoint.py
Only need log error info 1 time when load state_dict in distributed mode.
=> Fix multiple err_msg logging in distribuited mode

mmcv/utils/path.py
Usually, we put data into a `data` folder and put code into a `lib` folder. With `find_vcs_root` function can get the `data` folder easily. Example:
```python
root_dir = osp.join(find_vcs_root(__file__), 'data')
```
Signed-off-by: Zhipeng Han <hanzhipeng9@gmail.com>
=> [feat]: find root of Version Control Systems

.dockerignore, .travis.yml, Dockerfile, README.rst, requirements.txt, setup.py
This PR  changes install_requires.
1. Dependency on opencv-python is resolved in the same way as done in [albumentations]()https://github.com/albu/albumentations/blob/master/setup.py#L12) library. `opencv-python` is used if it has already been installed. Otherwise `opencv-python-headless` is used which is good for minimal container environments.
2. Cython is build-time dependency and is removed from install_requires
=> fix dependencies

mmcv/cnn/weight_init.py
The `constant_init` is used to initialize `BN` layer typically. If `BN` layer is instanced with `affine=False`, the `weight` will be `None`. Add code to process the case.
=> process the case that no weight in the module

mmcv/utils/misc.py
According to the docs, the second argument in `mmcv.slice_list` may be an integer as well, but the original implement dos not support `int`.
=> Fix int support in mmcv.slice_list

mmcv/__init__.py, mmcv/arraymisc/__init__.py, mmcv/cnn/__init__.py, mmcv/fileio/__init__.py, mmcv/image/__init__.py, mmcv/image/transforms/__init__.py, mmcv/runner/__init__.py, mmcv/runner/checkpoint.py, mmcv/runner/hooks/__init__.py, mmcv/runner/hooks/logger/wandb.py, mmcv/utils/__init__.py, mmcv/video/__init__.py, mmcv/visualization/__init__.py, tests/test_progressbar.py, tests/test_runner.py
The original implementation of `load_state_dict ` function directly copy the weights by their name, now it adopts the newest implementation of  `load_state_dict ` from PyTorch 1.3.1. Thus, it could use the `_load_from_state_dict` function implemented for each nn.module, which enables the version control during weight loading and provides flexibility.
This PR is related to the PR https://github.com/open-mmlab/mmdetection/pull/1894 for [mmdetection](https://github.com/open-mmlab/mmdetection) to enable the backward compatibility of `DCNModule`.
=> Load state dict

README.rst, mmcv/version.py, setup.py
This PR also fixes the installation with pip due to the missing of `requirements.txt`.
=> Remove support for python 3.4

mmcv/image/transforms/normalize.py, tests/test_image.py
About 3x speed up.
```python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import cv2                                                  
In [2]: import numpy as np                                          
In [3]: img = np.random.randn(100,200,3).astype(np.float32)         
In [4]: mean = np.array([1,2,3])                                    
In [5]: std = mean / 10                                             
In [6]: %timeit (img - mean) / std                                  
291 µs ± 1.53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops ea
ch)
In [7]: %timeit cv2.divide(cv2.subtract(img, mean.reshape(1,3)
...: .astype(np.float64)), …
```
=> Use cv2 to normalize img

.travis.yml, mmcv/image/__init__.py, mmcv/image/io.py, tests/test_image.py
🏃Work In Progress
Use TurboJPEG instead of cv2 for RGB image decoding and increase the speed of image decoding about 3 times. Still have several items to be improved:
=> Image decoding optimization

mmcv/version.py, tests/test_video.py
In some cases (`/tmp` is empty and sudo previledge is granted), the `/tmp` dir will be removed by calling `os.removedirs('/tmp/xxxx')`.
=> Fix a potential bug of removing temp dir

mmcv/utils/config.py, tests/data/config/l.py, tests/data/config/l4.py, tests/test_config.py
This PR added pretty_text in Config, which could print formated cfg. 
Note: pretty_text could be directly loaded with Config and result is the same as original cfg. 
For example,  in [mask_rcnn_r50_fpn_1x_coco.py](https://github.com/open-mmlab/mmdetection/blob/v2.0), 
```
cfg = Config.fromfile('configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py')
cfg.pretty_text
```
the output would be 
```
model=dict(
type='MaskRCNN',
pretrained='torchvision://resnet50',
backbone=dict(
type='ResNet',
depth=50,
num_stages=4,
out_indices=(0, 1, 2, 3),
frozen_stages=1,
norm_cfg=dict(
type='BN',
requires_grad=True),
norm_eval=True,
style='pytorch'),
neck=dict(
type='FPN',
in_channels=[256, 512, 1024, 2048],
out_channels=256,
num_outs=5),
rpn_head=dict(
type='RPNHead',
in_channels=256,
feat_channels=256, …
```
=> add pretty_text

mmcv/runner/hooks/__init__.py, mmcv/runner/hooks/logger/__init__.py, mmcv/runner/hooks/logger/mlflow.py, tests/test_hooks.py, tests/test_runner.py
This P.R. adds a new class to `mmcv.runner.hooks.logger` for logging metrics and (optionally) a trained model to [MLflow](https://www.mlflow.org/docs/latest/index.html); similar to existing options for pavi, wandb or tensorboard.
An unit test following the existing ones is included.
The `wandb` unit test has been moved from `test_runner `to `test_hooks`.
=> Add MlflowLoggerHook

mmcv/runner/hooks/logger/text.py
This pull request fixes the deadlock issue if processes have different `log_buffer.output` when using `TextLoggerHook` in distributed mode. More specifically, if process 0 has called log_buffer.clear() while other processes have not, the process 0 will not call `_get_max_memory()` (which calls `torch.distributed.reduce()`) in `TextLoggerHook` while others will call. Thus, the synchronization between processes will be broken.
=> Fix deadlock if processes have different log_buffer.output

mmcv/utils/registry.py, tests/test_registry.py
Old API:
```python
CATS = mmcv.Registry('cat')
@CATS.register_module
class BritishShorthair:
pass
```
New API:
```python
CATS = mmcv.Registry('cat')
@CATS.register_module()
class BritishShorthair:
pass
@CATS.register_module(name='CuteCat')
class Munchkin:
pass
```
=> Support specifying names for registry.register_module()

mmcv/cnn/__init__.py, mmcv/cnn/bricks/__init__.py, mmcv/cnn/bricks/activation.py, mmcv/cnn/bricks/conv.py, mmcv/cnn/bricks/conv_module.py, mmcv/cnn/bricks/norm.py, mmcv/cnn/bricks/padding.py, mmcv/cnn/bricks/registry.py, mmcv/cnn/bricks/scale.py, mmcv/cnn/bricks/upsample.py, mmcv/utils/registry.py, tests/test_cnn/test_build_layers.py, tests/test_cnn/test_conv_module.py, tests/test_cnn/test_scale.py, tests/test_registry.py
This PR moves some building bricks from other repos (e.g., mmdetection) to mmcv. Besides, we use registry instead of a dict to manage all modules.
- `ConvModule`
- `build_conv_layer`
- `build_norm_layer`
- `build_activation_layer`
- `build_upsample_layer`
- `build_padding_layer`
=> Add building bricks of cnn

mmcv/utils/config.py, tests/test_config.py
This PR made `Config.dump()` output in original file format for different config type.
=> Make Config.dump() output in original file

mmcv/cnn/bricks/upsample.py, tests/test_cnn/test_build_layers.py
Original `build_upsample_cfg` does not support to pass `args` and `kwargs`, this PR fix that.
=> Support to pass args to cnn bricks

mmcv/runner/checkpoint.py
This PR adds the pre-trained models of RegNetXs.
The model weights are converted from the model zoo of [Pycls](https://github.com/facebookresearch/pycls/blob/master/MODEL_ZOO.md).
=> Add regnetx links

mmcv/cnn/bricks/conv_module.py, tests/test_cnn/test_conv_module.py
When building `ConvModule` with activation function `nn.Tanh`, `inplace=True` is automatically added to `act_cfg`. However, `nn.Tanh` does not accept `inplace` argument.
This pull request fixes this by adding keyword `inplace` to `act_cfg` only when activation type is not `nn.Tanh`.
=> fix building ConvModule with Tanh activation

mmcv/parallel/collate.py
You are probably aware, but when training I am getting a few deprecation warnings:
`mmcv/mmcv/parallel/collate.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working`
These imports should be updated:
https://docs.python.org/3.8/library/collections.abc.html#collections.abc.Sequence
The note in 3.7 docs:
> Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.
=> Fix deprecation warning collections.abc

mmcv/runner/optimizer/default_constructor.py
This pull request changes the import source of `_BatchNorm` and `_InstanceNorm` in default_constructor.py from torch to mmcv.utils.parrots_wrapper.py.
=> Use parrots wrapper in optimizer constructor

mmcv/runner/hooks/optimizer.py
If the users specify grad_clip in the config, it's better to monitor the grad_norm so that one can judge if the training is stable or not from the grad_norm.
=> Add grad norm to the logger

mmcv/cnn/resnet.py, mmcv/cnn/vgg.py, mmcv/runner/dist_utils.py, mmcv/runner/hooks/momentum_updater.py, mmcv/utils/progressbar.py, mmcv/video/processing.py, tests/test_video/test_processing.py
```bash
$ pylint mmcv | grep unused
mmcv/video/processing.py:55:0: W0613: Unused argument 'kwargs' (unused-argument)
mmcv/video/processing.py:94:0: W0613: Unused argument 'kwargs' (unused-argument)
mmcv/video/processing.py:130:0: W0613: Unused argument 'kwargs' (unused-argument)
mmcv/cnn/weight_init.py:52:31: W0613: Unused argument 'bias' (unused-argument)
mmcv/cnn/resnet.py:32:17: W0613: Unused argument 'style' (unused-argument)
mmcv/cnn/resnet.py:174:8: W0612: Unused variable 'i' (unused-variable)
mmcv/cnn/vgg.py:144:15: W0612: Unused variable 'num_blocks' (unused-variable)
mmcv/utils/progressbar.py:178:0: W0613: Unused argument 'kwargs' (unused-argument)
mmcv/runner/dist_utils.py:36:0: W0613: Unused argument 'kwargs' (unused-argument)
mmcv/runner/hooks/momentum_updater.py:7:0: W0613: …
```
=> Remove more unused things

mmcv/runner/hooks/optimizer.py
In pytorch-1.4&pytorch-1.5 the returning value of `clip_grad_norm` is torch.Tensor (https://github.com/pytorch/pytorch/blob/4ff3872a2099993bf7e8c588f7182f3df777205b/torch/nn/utils/clip_grad.py#L30), whereas in previous versions the returning value is a itemized float value https://github.com/pytorch/pytorch/blob/6590ecf1c9d30c2cfa5dbc762ce03672275ac8af/torch/nn/utils/clip_grad.py#L33. This  PR helps fix this bug.
=> fix possible bugs brought by dumping grad_norm to the logger

mmcv/runner/hooks/logger/base.py, mmcv/runner/hooks/logger/pavi.py, mmcv/runner/hooks/logger/tensorboard.py, mmcv/runner/hooks/logger/text.py, mmcv/runner/iter_based_runner.py
The new iter-based runner may have some potential bugs in using `inner_iter` and we just make `inner_iter` have correct manner and other related hooks(logger hooks) called with conditions on `iter`.
=> fix bug in using inner iter when by_epcoh==True

mmcv/runner/checkpoint.py
The original `load_checkpoint` only support OrderedDict checkpoints. However, there are exceptions (e.g. user-defined checkpoint in dict format, shufflenet checkpoints (https://download.pytorch.org/models/shufflenetv2_x0.5-f707e7126e.pth))
This PR helps support checkpoints in dict format.
=> load_checkpoint support normal dict checkpoints

mmcv/parallel/__init__.py, mmcv/parallel/distributed_deprecated.py, mmcv/parallel/registry.py, mmcv/parallel/utils.py, mmcv/runner/base_runner.py, mmcv/runner/checkpoint.py, tests/test_parallel.py
`DataParallel`, `DistributedDataParallel`, `MMDistributedDataParallel` are conceptually module wrappers. This PR add a module wrapper registry to allow user-registered module wrapper.
=> Add module wrapper registry

mmcv/runner/optimizer/default_constructor.py, tests/test_optimizer.py
It would throws a `TypeError` when `weight_decay` is not specified but `custom_keys` are specified in `paramwise_cfg`.
=> Fix potential bug in DefaultOptimizerConstructor

mmcv/utils/__init__.py
This PR enables users to use some of the pytorch-independent utilities directly.
=> Lite version: use mmcv without installing pytorch as a requirement

mmcv/runner/utils.py
In generative model, we will need to set different random seeds in different thread when using dist training. Thus, this pr is for generate different noise for GAN model.
=> add set_random_seed and use rank shift feature

mmcv/runner/checkpoint.py, tests/test_runner/test_checkpoint.py
This merge request modifies the `mmcv.runner.checkpoint.save_checkpoint()`. Originally, the function only remove `module` of state_dict keys from the outer module wrapper. We modify the function to remove all the `module` of state_dict keys generated by module wrappers (even module wrapper is embedded within the model).
=> Remove all module wrapper's module when saving checkpoint

mmcv/visualization/image.py
in some version of opencv,
https://github.com/open-mmlab/mmcv/blob/2b876bc7a7066ca5941bda9e5841147dfcc5904a/mmcv/visualization/image.py#L130
will raise a error
`imshow_det_bboxes(
img, left_top, right_bottom, bbox_color, thickness=thickness)
TypeError: an integer is required (got type tuple)`
=> fix a bug in some opencv version

mmcv/utils/config.py
modied mmcv/utils/config.py use print the error log when validate the syntax of config file, otherwise it is hard to debug for users.
=> [feat]add error log in config validate check

mmcv/runner/hooks/logger/text.py
This pull request fix `_get_max_memory` throw `has no attribute 'output_device'` error when model has no attribute `output_device`.
`output_device` is an attribute from DDP (DistributedDataParallel) module. If model passed to mmcv runners is not wrapped by DDP, it does not have 'output_device'. This  PR fix this by returning None if model has no attribute 'output_device'.
=> Fix 'has no attribute' error when model is not wrapped by DDP

mmcv/__init__.py, mmcv/onnx/__init__.py, mmcv/onnx/onnx_utils/symbolic_helper.py, mmcv/onnx/symbolic.py, mmcv/ops/nms.py
This PR has the following change:
[1] Add symbolic for NMS Function which is used for exporting ONNX 
[2] Add symbolic.py and symbolic_helper.py, which are modified from Pytorch. These files are used for some special operators which can not be converted to ONNX correctly while using Pytorch
=> support converting pytorch to onnx

mmcv/runner/__init__.py, mmcv/runner/hooks/__init__.py, mmcv/runner/hooks/optimizer.py
This PR added Fp16Optimizer into the registry. In this way, we could directly build a Fp16Optimizer from config.
=> Add Fp16Optimizer into registry

mmcv/utils/config.py
fix: close temp file after creating it to avoid permission problems on windows.
`Traceback (most recent call last):
File "D:/projects/mmsegmentation/tools/get_flops.py", line 56, in <module>
main()
File "D:/projects/mmsegmentation/tools/get_flops.py", line 33, in main
cfg = Config.fromfile(args.config)
File "d:\projects\mmcv\mmcv\utils\config.py", line 207, in fromfile
use_predefined_variables)
File "d:\projects\mmcv\mmcv\utils\config.py", line 130, in _file2dict
temp_config_file.name)
File "d:\projects\mmcv\mmcv\utils\config.py", line 110, in _substitute_predefined_vars
with open(temp_config_name, 'w') as tmp_config_file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxxxxxxxxx\\AppData\\Local\\Temp\\tmpkzk7pd02\\tmpc7aaepmu.py'
`
**The solution** is to immediately close the …
=> fix: close temp file after creating it to avoid permission problem.

mmcv/runner/epoch_based_runner.py, mmcv/runner/iter_based_runner.py, tests/test_runner/test_runner.py
This PR modifies:
* In `EpochBasedRunner`, if `runner.meta` is not None, add the meta to checkpoint's meta.
* In `IterBasedRunner`, fix `runner.save_checkpoint()` when `runner.meta is None`.
=> Add runner.meta to checkpoint in save_checkpoint()

mmcv/runner/hooks/lr_updater.py
This PR changes the code to make `self.warmup_iters` assigned in `before_run` function in class `LrUpdaterHook`. The original code can not run when `self.warmup_by_epoch = True` and `self.by_epoch=False`.
=> Assign `self.warmup_iters` in `before_run` function

mmcv/runner/hooks/lr_updater.py
This PR fixes bug for `self.warmup_iters` when `self.warmup_by_epoch` in `before_run`, since at the stage `before_run`, the runner could not get the `data_loader`. So, This PR moves it to `before_train_epoch` and uses `if self.warmup_iters is None:` to make the `self.warmup_iters` assigned only Once.
=> Fix bug for `self.warmup_iters` when warmup_by_epoch

mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/csrc/pytorch/sync_bn.cpp, mmcv/ops/sync_bn.py, tests/test_ops/test_syncbn.py
1. parrots' cpp extension needs input tensors locate before output tensors.
2. parrots' tensor.requires_grad is False in Function.
=> fix syncbn parameter order mismatch and parrots bug

mmcv/parallel/_functions.py, mmcv/parallel/data_parallel.py, mmcv/parallel/scatter_gather.py
Fix https://github.com/open-mmlab/mmdetection/issues/1501
Fix https://github.com/open-mmlab/mmdetection/issues/3048
A RetinaNet is tested with three modes: multi-GPU distributed testing, single-GPU testing with MMDataParallel, and CPU testing with MMDataParallel. The model achieves similar AP under these three modes.
=> Fix mmcv-dataparallel

mmcv/ops/csrc/pytorch/carafe_naive_cuda.cu, mmcv/ops/csrc/pytorch/pybind.cpp
This was required for me to build on windows on VS17/19, but several function prototypes in the pybind11 file did not match those in neighboring files due to differences in returning ints vs voids, and one const inconsistency on recent code
=> Fix inconsistent return types in pybind11 function prototypes

.github/workflows/build.yml
This PR fixes the bug in github action caused by the weird cublas installation path. When installing CUDA, `libcublas10_10.2.2.214-1_amd64.deb` and  `libcublas-dev_10.2.2.214-1_amd64.deb`will be automatically installed due to compatibility issues. However, these two libraries will be installed in `/usr/local/cuda-10.2` rather than the expected `/usr/local/cuda-10.1`, although we install CUDA-10.1. Thus, when compiling the CUDA extensions, it will raise `cublas_v2.h is not found` error. This is fixed by simply copying the files from `/usr/local/cuda-10.2` to `/usr/local/cuda-10.1`.
=> [feature] Use cu92 & ubuntu1604 for torch 1.3.1

mmcv/visualization/image.py
This PR enables `imshow_det_bboxes` function to return the processes image array with bbox drawn on it. The users may need this array for further processing.
=> Allow imshow_det_bboxes to return image with bboxes.

README.md, mmcv/ops/csrc/pytorch/focal_loss_cuda.cu
Fix #534, Fix #533 .
The change has been verified in Linux and causes no bugs.
=> [fix] Fix compilation bug in windows and add instruction for windows

mmcv/image/__init__.py, mmcv/image/photometric.py, tests/test_image/test_photometric.py
This PR implements color augmentations which only transforms image (e.g. color, equalize, sharpness) in mmcv.
=> Supports Color augmentation.

mmcv/image/__init__.py, mmcv/image/photometric.py, tests/test_image/test_photometric.py
This PR implements equalize augmentation in mmcv.
=> Supports Equalize Augmentation.

mmcv/parallel/collate.py
When single GPU testing with batch size > 1 and the length of the dataset can't be divisible by the batch size, this assertion will report an error. It seems it can be safely removed to yield the correct result.
=> Remove assertion

mmcv/image/__init__.py, mmcv/image/photometric.py, tests/test_image/test_photometric.py
This PR implements brightness and contrast augmentations in mmcv.
=> Supports brightness and contrast augmentations

mmcv/utils/registry.py, tests/test_utils/test_registry.py
This P.R. updates `build_from_cfg` in order to allow `type` being set with `default_args`
=> Allow type to be default arg

mmcv/ops/deprecated_wrappers.py
Added missing `self` in deprecated wrappers to solve mmdetection [#3785](https://github.com/open-mmlab/mmdetection/issues/3785).
=> fix deprecated wrappers exiting bug

mmcv/version.py
- Implement `Conv2dAdaptivePadding`, which is the same op as 2D convolution in tensorflow with `padding` set to "same". (#529)
- Support reading video from url (#531)
- Add `imtranslate`, `imequalize`, `adjust_color`, `adjust_brightness`, `adjust_contrast` augmentation. (#538, #542, #543, #546)
- Add switch for onnx exporter. (#564)
- Allow `type` to be `default_args` in `build_from_cfg`. (#558)
- Expose `wrap_fp16_model` to mmcv.runner.  (#555)
- Move op wrappers into bricks and use wrappers in registry (#550)
- Support multiple interpolation modes for `imrotate` (#545)
- Fix the init method of deprecated wrappers. (#567)
- Fix DCN bug in parrots. (#562, #563, #565)
- Use copy instead of symlink on windows. (#557)
- Remove assertion for batch size and samples_per_gpu. (#549)
- Fix …
=> Bump version to 1.1.3

mmcv/runner/base_runner.py, mmcv/runner/epoch_based_runner.py
=> merge the calling of train/val_step and batch_processor into run_iter

mmcv/runner/hooks/logger/mlflow.py, mmcv/runner/hooks/logger/wandb.py
Some logger hooks were missing the `by_epoch` argument making them not compatible with `IterBasedRunner`
=> Add missing by_epoch arg

mmcv/runner/__init__.py, mmcv/runner/base_runner.py, mmcv/runner/builder.py, mmcv/runner/epoch_based_runner.py, mmcv/runner/iter_based_runner.py, tests/test_runner/test_hooks.py, tests/test_runner/test_runner.py
This P.R. adds a new method `build_runner` and a new Registry object: `RUNNERS` for managing runner types.
This allows to specify runner type (and corresponding parameters) via configuration files.
The `max_iters` and `max_epochs` arguments have been moved from `run` to `__init__` (this change is backwards compatible with deprecation warning).
I don't know if there was a use case that needed to have them in `run` but in all downstream repos (mmdet, mmseg, etc) those args were parsed from config so i think it makes sense to set them during instantiation.
Discussed in https://github.com/open-mmlab/mmsegmentation/pull/118
=> Add runner builder

mmcv/ops/roi_align.py
Hi
torchvision.ops.roi_align support aligned flag now. [https://github.com/pytorch/vision/pull/1908](https://github.com/pytorch/vision/pull/1908).
This PR enable aligned flag when use_torchvision=True in mmcv.ops.RoIAlign
=> add torchvision roi_align with aligned=True

mmcv/parallel/data_parallel.py
"please use MMDistributedDataParallelinstead." -> "please use MMDistributedDataParallel instead."
=> Fix a typo in warning message

mmcv/utils/config.py, tests/data/config/q.py, tests/data/config/r.py, tests/test_utils/test_config.py
Proposal by @innerlee in https://github.com/open-mmlab/mmaction2/pull/212
=> import_modules_from_strings when loading cfg from file

mmcv/runner/iter_based_runner.py
The iter-time hook is called with a wrong placement (before `next(dataloader)`).
=> [Bug] fix iter-time-hook bug when meeting iter-based runner

mmcv/cnn/__init__.py, mmcv/cnn/bricks/__init__.py, mmcv/cnn/bricks/wrappers.py, tests/test_cnn/test_wrappers.py
This PR adds `MaxPool2d` and `ConvTranspose3d` in `mmcv/cnn/bricks/wrappers.py`.
ref: [MaxPool3d](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool3d.html#torch.nn.MaxPool3d), [ConvTrranspose3d](https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose3d.html#torch.nn.ConvTranspose3d), [Conv3d](https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html#torch.nn.Conv3d)
=> [Feature] Add 3D support in wrapper

mmcv/cnn/utils/flops_counter.py
Fix https://github.com/open-mmlab/mmcv/issues/675
Running the script in that issue
before:
```bash
Sequential(
(0): Conv2d(30, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
(1): ConvTranspose2d(30, 30, kernel_size=(3, 3), stride=(2, 2), output_padding=(1, 1), bias=False)
)
Sequential(
(0): Conv2d(30, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
(1): ConvTranspose2d(30, 30, kernel_size=(3, 3), stride=(2, 2), output_padding=(1, 1), bias=False)
)
Sequential(
0.008 M, 50.000% Params, 0.531 GFLOPs, 100.000% FLOPs, 
(0): Conv2d(0.008 M, 50.000% Params, 0.531 GFLOPs, 100.000% FLOPs, 30, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
(1): ConvTranspose2d(0.0 M, 0.000% Params, 0.0 GFLOPs, 0.000% FLOPs, 30, 30, kernel_size=(3, 3), …
```
=> Support mmcv bricks in flops compuation

mmcv/cnn/bricks/conv_module.py
This PR fix the comment of init_weights in ``ConvModule`` about PyTorch original conv layers.
=> fix the comment of init_weights in ``ConvModule``

mmcv/ops/csrc/pytorch/pybind.cpp, tests/test_ops/test_nms_rotated.py
Fixes #709 
Two problems for my view:
1. Argument type of `nms_rotate` mismatch in `pybind.cpp` and `nms_rorate.cpp`, the latter is with `const`  while the former isn't.
2. Argument in python unittest mismatch, seems `score` is merged into `box` as 6-th column.
=> Fix some bug as well as unit test for nms_rotate

mmcv/ops/roi_align.py
Some complex head architecture may cause grad_output uncontiguous, eg.dii head in sparsercnn
=> fix grad_output uncontiguous

.github/workflows/build.yml, mmcv/utils/__init__.py, mmcv/utils/testing.py, tests/test_utils/test_testing.py
Add common testing function of MM repos
=> Add common testing function of MM repos

mmcv/ops/csrc/tensorrt/plugins/trt_plugin.cpp, mmcv/ops/csrc/tensorrt/plugins/trt_scatternd.cpp, mmcv/ops/csrc/tensorrt/plugins/trt_scatternd_kernel.cu, mmcv/ops/csrc/tensorrt/trt_cuda_helper.cuh, mmcv/ops/csrc/tensorrt/trt_plugin_helper.hpp, mmcv/ops/csrc/tensorrt/trt_scatternd.hpp, tests/test_ops/test_tensorrt.py
This PR add support to ONNX [ScatterND](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ScatterND)
Support convert of pytorch code such as:
```python
tensor[:, -2:] += 1
```
=> [Feature] : Add ScatterND TensorRT Plugin

docs/conf.py, docs/tensorrt_plugin.md
This PR adds a short document for TensorRT plugins in `mmcv`.
=> [Doc]: add a short document for TensorRT plugins in mmcv

mmcv/ops/csrc/onnxruntime/cpu/nms.cpp, mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp, mmcv/ops/csrc/onnxruntime/nms.h, mmcv/ops/nms.py, tests/test_ops/test_onnx.py
add onnxruntime custom op: nms
=> add ort nms op

mmcv/onnx/onnx_utils/symbolic_helper.py
Fix  [Issue #451](https://github.com/open-mmlab/mmpose/issues/451) in MMPose: pytorch2onnx failed with PyTorch>=1.7.0 for `hrnet_w32_coco_256x192.py`. This problem was once metioned  in [#4221](https://github.com/open-mmlab/mmdetection/issues/4221) as well.
This PR includes:
1. update `_interpolate_get_scales_if_available` to support pytorch2onnx with PyTorch<=1.7.0
=> [Fix]: parse scales of list in PyTorch==1.7.0 (#451 in MMPose)

mmcv/ops/csrc/onnxruntime/cpu/nms.cpp, mmcv/ops/nms.py
This PR adds header file for ` std::iota` in PR #803.
Error message when install from source:
```
/mmcv/mmcv/ops/csrc/onnxruntime/cpu/nms.cpp:57:8: error: ‘iota’ i
368        std::iota(order.begin(), order.end(), 0);
```
=> [Fix]: add header file for std::iota(#803)

mmcv/visualization/image.py
=> fix: imshow_bboxes fails with incontiguous img

mmcv/ops/csrc/pytorch/deform_conv_cuda.cu
=> fix bug of DCN

mmcv/cnn/utils/weight_init.py
use kwargs instead of the same arguments in `BaseInit`, and fix docstring and error msg.
=> fix weight_init.py

mmcv/utils/registry.py, tests/test_utils/test_registry.py
Description of the PR:
It add more error information about the object class when building from cfg
Previous error info:
> TypeError: __init__() got an unexpected keyword argument 'non_existing_arg'
Current error info:
> TypeError: ResNet: __init__() got an unexpected keyword argument 'non_existing_arg'
=> Add more error info in build_from_cfg

mmcv/runner/base_runner.py
Fixes [#837](https://github.com/open-mmlab/mmcv/issues/837)
=> add register_itertimer_hook function

docs/cnn.md, mmcv/cnn/bricks/activation.py
The VisionTransformer need GELU activation function.
=> Add GELU activation function

mmcv/runner/base_runner.py, mmcv/utils/config.py, tests/test_utils/test_config.py
reslove: https://github.com/open-mmlab/mmdetection/issues/3676
=> Fix the iter error when the number of GPUs is different during resume

.github/workflows/build.yml, mmcv/onnx/onnx_utils/symbolic_helper.py, tests/test_ops/test_onnx.py
Fix issue in mmdet issue [4646](https://github.com/open-mmlab/mmdetection/issues/4646)
This PR includes:
1. Fix  `interpolate` op's pytorch2onnx conversion error with PyTorch==1.6.0
2. Add unit test of pytorch2onnx for `interpolate` op
=> Fix pytorch2onnx failed for interpolate op with PyTorch==1.6.0(mmdet#4646)

mmcv/video/io.py
Ref: https://github.com/open-mmlab/mmcv/pull/847
=> Polish video/io.py to remove redundant codes

mmcv/cnn/utils/weight_init.py, mmcv/runner/base_runner.py, mmcv/runner/checkpoint.py, tests/test_runner/test_checkpoint.py, tests/test_runner/test_hooks.py
This would be useful when one would like to incorporate other models into open-mmlab series, e.g. when using simple encoder-decoder structure in mmediting, the keyword backbone may need to be added for the checkpoint. Then one can set the addword='backbone'.
=> [Feature] Support revise_keys in load_checkpoint().

mmcv/fileio/file_client.py, tests/test_fileclient.py
add HTTP and HTTPs fileio support.
=> add HTTP backend

mmcv/image/photometric.py, tests/test_image/test_photometric.py
Hi,
In this pull request, bugs in `imequalize`, `adjust_brightness` and `adjust_contrast` are fixed and unittests are updated.
For `imequalize`, `astpye` is missing, which will cause the output to be in wrong type(int64). #861 
For `adjust_brightness` and `adjust_contrast`, factor could be larger than 1. Clipping is needed since we use float32 to calculate.
Pls kindly take a look. Thank you.
=> [Bug]Fix bugs in imequalize, adjust_brightness and adjust_contrast

mmcv/image/__init__.py, mmcv/image/photometric.py, tests/test_image/test_photometric.py
Hi, 
In this pull request, `adjust_sharpness` is added for data augmentation. Pls kindly take a look. Thx.
=> [Feature] Add adjust sharpness

tests/test_ops/test_tensorrt.py
This PR fix test units of `nms` and `batched_nms` in  `test_tensorrt.py`.
=> fix test unit of nms and batched_nms for tensorrt

mmcv/parallel/distributed.py
This PR adds a method named `to_kwargs`  to `MMDistributedDataParallel`.
`DistributedDataParallel` in PyTorch 1.8 use `to_kwargs` instead of `scatter` to move all tensor in dataflow to 
the device. it is necessary to overload this function as `scatter`.
None
Fixes open-mmlab/mmdetection#4737
=> fix scatter in pytorch18

mmcv/runner/base_module.py
Hi,
In this pr, I change the `is_init` flag function. When it is True means that `init_weight` has been called.
Thank you @jshilong   for your kind suggestion.
=> Revise function of is_init flag in BaseModule

mmcv/cnn/utils/flops_counter.py, tests/test_cnn/test_flops_counter.py
Related Issue：https://github.com/open-mmlab/mmcv/issues/886
**Support:**
1. Support to calculate FLOPs of GroupNorm, InstanceNorm1d, InstanceNorm2d, InstanceNorm3d, LayerNorm
**Discussion:**
**1. how to support torch.bmm**
Now we only support to calculate FLOPs of those modules inherited from `nn.Module`. Therefore, operations which are not inherited from `nn.Module` are not supported, such as `torch.bmm`, `torch.nn.functional.conv2d`.
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from mmcv.cnn.utils import get_model_complexity_info
class Dummy(nn.Module):
def __init__(self):
super().__init__()
self.conv1 = nn.Conv2d(3, 8, 3)
self.conv2 = nn.Conv2d(8, 256, 3)
self.conv3 = nn.Conv2d(256, 8, 3)
self.avg_pool = nn.AdaptiveAvgPool2d((1, 1))
self.flatten = …
```
=> [Feature] support to calculate FLOPs of GN, IN, LN

mmcv/cnn/bricks/conv_module.py, tests/test_cnn/test_conv_module.py
This PR fixes the potential bug of `ConvModule` when specifying the `norm_cfg` as None.
The original implementation would raise the `ConvModule' object has no attribute 'norm` when you try to call
`self.norm` when passing `norm_cfg` as None.
I believe the original design is not reasonable, because you can find an attribute named `norm` by `dir(instance)` or `instance.__dict__`,  but when you access it by `instance.norm`, it will raise an error. 
Closes #871
=> fix bug of convmodule

mmcv/cnn/utils/weight_init.py, tests/test_cnn/test_weight_init.py, tests/test_runner/test_basemodule.py
Hi,
As developers would like to only initialize parameters with attribute names, I just revise the initialization mechanism. If we don't define `layer` key or `override` key, it will not initialize anything; if we define `override` but don't define `layer`, it will initialize parameters with the attribute name in `override`; if we only define `layer`, it just initialize the layer in `layer` key; if we define `override` and `layer`, `override` has higher priority and will override initialization mechanism.
Moreover, for ease of use, if we only define `override`, and `override` without `type` key, the `type` key and other kwargs will merge in `override`.
=> [Refactoring] Revise function of layers and override keys in init_cfg

mmcv/image/__init__.py, mmcv/image/geometric.py, mmcv/image/photometric.py, tests/test_image/test_geometric.py, tests/test_image/test_photometric.py
Hi,
In this pull request, cutout and change the lighting are added. Pls kindly take a look. Thank you.
=> [Feature] Add cutout and lighting

mmcv/runner/base_module.py
Add the class name of the module to the warning in ``init_weight`` of BaseModule.
=> add more detail of warning in basemodule

mmcv/cnn/utils/weight_init.py
This PR fixes the bug in the `initialize` function, which will change the original init_cfg after override some keys.
This behavior will cause an error when one config is used in many other modules as the config will be changed after it has been used once.
One test case that will cause the failure is [here](https://github.com/hhaAndroid/mmdetection/blob/refactor_init/tests/test_models/test_backbones/test_resnet.py#L622).
=> [Fix]: Fix initialization bug of override cfg

mmcv/runner/hooks/lr_updater.py, mmcv/runner/hooks/momentum_updater.py, tests/test_runner/test_hooks.py
Related Issue: https://github.com/open-mmlab/mmcv/issues/896
=> [Feature] Add OneCycleLrUpdaterHook

mmcv/onnx/onnx_utils/symbolic_helper.py
https://github.com/open-mmlab/mmcv/blob/9d80f56ae8c416556f08d0e04d03785ac036c9c7/mmcv/onnx/onnx_utils/symbolic_helper.py#L232
scales[0] could be 'TensorType' with sizes = [2].
Tested on pytorch==1.8.1
=> Fix onnx interpolate conversion

mmcv/runner/hooks/lr_updater.py, mmcv/runner/hooks/momentum_updater.py, tests/test_runner/test_hooks.py
Fix bug of https://github.com/open-mmlab/mmcv/issues/887
**[Next PR]**
I will do more unittest in https://github.com/open-mmlab/mmcv/blob/master/tests/test_runner/test_hooks.py.
But, maybe we should refactor the code `test_hooks.py` to make the test logic clearer.
```
├── test_basemodule.py
├── test_checkpoint.py
├── test_dist_utils.py
├── test_fp16.py
├── test_hooks.py
├── test_optimizer.py
├── test_runner.py
└── test_utils.py
```
to
```
├── test_basemodule.py
├── test_checkpoint.py
├── test_dist_utils.py
├── test_fp16.py
├── test_hooks
│   ├── test_checkpoint_hook.py
│   └── test_lr_updater_hook.py
├── test_hooks.py
├── test_optimizer.py
├── test_runner.py
└── test_utils.py
```
=> [Fix] Fix bug of lr updater hook

mmcv/cnn/utils/weight_init.py, tests/test_cnn/test_weight_init.py
deep copy `override_` to improve the robustness
=> [Fix] Revise override in init_cfg

.pre-commit-config.yaml, mmcv/ops/csrc/deform_conv_cuda_kernel.cuh, mmcv/ops/csrc/deform_roi_pool_cuda_kernel.cuh, mmcv/ops/csrc/modulated_deform_conv_cuda_kernel.cuh, mmcv/ops/csrc/roi_align_cuda_kernel.cuh, mmcv/ops/csrc/roi_pool_cuda_kernel.cuh
to eliminate cuda compilation errors in the latest version of Visual Studio 16.9
Code modified to address the following issues
Fixes #888
=> fix cuda compile error

mmcv/ops/deform_conv.py, tests/test_ops/test_deform_conv.py
=> [Bug] Fix DeformConv2d bias error and add tests

mmcv/runner/epoch_based_runner.py
=> [Fix] Fix train error in EpochBasedRunner

mmcv/cnn/bricks/transformer.py
Actually `init_cfg` would be set in BaseModule, `self.init_cg` in subclass is redundant．
##BC-breaking
None
=> Remove redundant self.init_cfg

setup.py
When I compile mmcv with custom op on a machine that does not have cuda installed, I will encounter the following error：
So I modified the code to get the cuda header file path when compiling Ort custom op in setup.py
=> Compile mmcv with custom op when not using cuda

mmcv/runner/base_module.py
I think the existence of attributes in an instance  should not depend on the value of the arguments. So I change the all `hasattr(self, 'init_cfg')` to `self.init_cfg` in BaseModule.
None
=> fix init cfg

mmcv/cnn/bricks/transformer.py
The original citation of the paper On Layer Normalization in the Transformer Architecture <https://arxiv.org/abs/2007.08103> is wrong.
It should be <https://arxiv.org/abs/2002.04745>
=> Incorrect citation in transformer documentation.

mmcv/ops/fused_bias_leakyrelu.py
In fp16 training with Apex, the `fused_bias_leakyrelu` module will raise TypeError in forwarding and backward procedures.
Just add the safe `.to(x.dtype)` operation.
=> [Enhancement] fix data type in fused-bias-leakyrelu for apex fp16 training

mmcv/cnn/builder.py
Due to parameter initialization, `mmcv.runner.Sequential` needs to be used.
refer to https://github.com/open-mmlab/mmdetection/pull/5059
=> Replace nn.Sequential due to parameter initialization.

mmcv/runner/fp16_utils.py, mmcv/runner/hooks/optimizer.py
This PR enables PyTorch official implementation for automatic mixed-precision training.
It replaces the original [Pull Request](https://github.com/open-mmlab/mmcv/pull/791) due to some accident.
=> Support auto_fp16 using torch.cuda.amp when PyTorch >= 1.6.0

mmcv/engine/test.py
=> [Fix] Use len(result) as batch size

mmcv/ops/csrc/parrots/roi_pool_parrots.cpp, mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/fused_bias_leakyrelu.py
We find a pybind exporting bug in fused_bias_leakyrelu and upfirdn2d sothat these operators cannot be used in pytorch. This PR can fix it.
By the way, we fix a minor bug in roi_pool which will cause compiling error when using parrots-nocuda.
=> [Fix] Fix pybind exporting bug in fused_bias_leakyrelu and upfirdn2d

docs/onnxruntime_custom_ops.md, docs/onnxruntime_op.md, mmcv/ops/corner_pool.py, mmcv/ops/csrc/onnxruntime/corner_pool.h, mmcv/ops/csrc/onnxruntime/cpu/corner_pool.cpp, mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp, tests/test_ops/test_onnx.py
Hi, this PR supports to export corner_pool related custom operators (`TopPool`,`BottomPool`,`LeftPool`,`RightPool` ) to onnx, and run it with onnxruntime.
It's working in process during my free time.
=> Support corner_pool related custom operators for onnxruntime in mmcv

docs/onnxruntime_custom_ops.md, docs/onnxruntime_op.md, mmcv/onnx/symbolic.py, mmcv/ops/corner_pool.py, mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp, mmcv/ops/csrc/onnxruntime/cpu/reduce_ops.cpp, mmcv/ops/csrc/onnxruntime/reduce_ops.h, mmcv/ops/nms.py, tests/test_ops/test_onnx.py
Hi, this PR tries to implement custom operator `mmcv::cummax` and `mmcv::cummin`, which supports to export `torch.cummax` and `torch.cummin` to onnx format, and run it with onnxruntime.
`mmcv::cummax` is a more general operation and an extension to previous [`mmcv::CornerPool`](https://github.com/open-mmlab/mmcv/pull/997), since the former supports arbitrary tensor shapes while the latter only supports for 4-D input tensor.
Based on the customized `mmcv::cummax` and `mmcv::CornerPool` operation, CornerNet in MMDet might be exportable to onnx for various pytorch version.
=> Support custom operators cummax and cummin for onnxruntime

mmcv/utils/__init__.py, mmcv/utils/testing.py, tests/data/scripts/hello.py, tests/test_utils/test_testing.py
This function can be used to check stand-alone scripts, without tweaking `sys.path` manually. Moreover, it will increase test coverage for codes the script touches.
=> Add test util for checking stand-alone python scripts

mmcv/ops/deform_conv.py
Fix https://github.com/open-mmlab/mmcv/issues/1004
Cast DCN weights by type_as, not by autocast.
No.
=> [Fix] Fix DCN fp16

mmcv/runner/hooks/lr_updater.py, mmcv/runner/hooks/momentum_updater.py, tests/test_runner/test_hooks.py
Similar to StepLRUpdaterHook, in 3D point cloud tasks, we also need to update the momentum of optimizers in a step manner.
Add a `StepMomentumUpdaterHook` class.
No.
Similar to `StepLrUpdaterHook`.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or …
=> [Enhance] Add step momentum updater to support MMDet3D

mmcv/runner/base_runner.py, mmcv/runner/hooks/evaluation.py, tests/test_runner/test_eval_hook.py
This PR is to load `hook_msgs` meta information saved in checkpoint which helps to store the `best` related information for evaluation
=> Load `hook_msgs` when resume checkpoint

mmcv/runner/base_module.py
In the original implementation, when init a module with the pre-train model,
https://github.com/open-mmlab/mmcv/blob/c77e95a65f0128c8faee15f0bc301744320d3609/mmcv/runner/base_module.py#L44
if there are children who have init_weights, the pretrain model would be overridden which is not reasonable.
Retune when find it is loading a pre-train model.
None
=> fix basemodule

mmcv/ops/nms.py, tests/test_ops/test_nms.py
In the original implementation,
https://github.com/open-mmlab/mmcv/blob/c77e95a65f0128c8faee15f0bc301744320d3609/mmcv/ops/nms.py#L296
Some type of nms such as softnms would reweight the score in `nms_op`, so we should use the score in `dets`  
None
=> fix softnms

examples/train_cifar10.py, mmcv/runner/base_runner.py, tests/test_runner/test_hooks.py
Refer to https://github.com/open-mmlab/mmcv/issues/967
I noticed that mmcv hooks already have priority. Therefore, I assign different priorities to default hooks, so that, we can use priority value to indicate when a hook should run.
For example, I add a custom hook as:
```
@HOOKS.register_module()
class CustomHook(Hook):
def __init__(self, p) -> None:
super().__init__()
self.p = p
def __repr__(self) -> str:
return f'<CustomHook> with priority {self.p}'
```
And edit the `base_runner.call_hook` function to show the effect.
```
def call_hook(self, fn_name):
"""Call all hooks.
Args:
fn_name (str): The function name in each hook to be called, such as
"before_train_epoch".
"""
self.logger.info('-------------------- start call hook -------------------- ')
for hook in self._hooks: …
```
=> Add custom hook by config file

.pre-commit-config.yaml, mmcv/utils/config.py
On Windows :
```python
with open("some_file", r) as f:
f.read()
```
will decode the content of the file based on windows's system language setting. 
Using `rb` mode then decode within python will force using utf-8.
note: the ruby precommit hook does not work on windows and I will recover it when everything other is good before actual merge.
=> [Fix] Read in rb mode then decode

mmcv/runner/hooks/logger/mlflow.py, mmcv/runner/hooks/logger/pavi.py, mmcv/runner/hooks/logger/tensorboard.py, mmcv/runner/hooks/logger/wandb.py
When the users want to check multi-logs like both the CLI and the other (like tensorboard, wandb, mlflow), current implementation may be missing some values because of their `reset_flag` option. This PR fixed these bugs.
this PR includes 2 commits.
1. `LoggerHook.before_run(runner)` set a flag whether `self` is the last logger or not. Then, other `LoggerHook`s have to call this method.
2. The `reset_flag`s should be initialized `False` in order to `before_run()` works well.
nothing.
For example, using `MlflowLoggerHook` and `TextLoggerHook` as follows:
```py
from mmcv.runner import IterBasedRunner
from mmcv.runner.hooks.logger.text import TextLoggerHook
from mmcv.runner.hooks.logger.mlflow import MlflowLoggerHook
from logging import Logger
class Model:
def train_step(self, *args, …
```
=> Fix a bug where logs are missing when two or more loggers were set

mmcv/cnn/bricks/generalized_attention.py, tests/test_cnn/test_generalized_attention.py
Fix open-mmlab/mmdetection#1241.
The function _get_position_embedding_ in _GeneralizedAttention_ returns float32 values, even if in fp16 mode.
- Cast the return values of _get_position_embedding_ function
- Add fp16 unit tests for _GeneralizedAttention_  with attention_type='1111'.
This bug does not exists in pytorch >= 1.6.0 and mmcv >= 1.3.2. It is not a bug with torch.cuda.amp.autocast applied. 
No
=> [Fix] fix generalized attention fp16

mmcv/runner/__init__.py, mmcv/runner/hooks/__init__.py, mmcv/runner/hooks/logger/__init__.py, mmcv/runner/hooks/logger/neptune.py, tests/test_runner/test_hooks.py
We want to use mmdetection with neptune.ai. This PR adds support to neptune.ai logging.
Added NeptuneLoggerHook
No breaking changes
=> add neptune.ai logger hook

mmcv/ops/deform_conv.py, mmcv/ops/modulated_deform_conv.py, tests/test_ops/test_deform_conv.py, tests/test_ops/test_modulated_deform_conv.py
mmcv 1.3.2 supports automatic mixed precision with pytorch >= 1.6.0  but the CUDA ops don't support it now, resulting in some runtime errors like #1004 and #1028.
#1014 fixes the bug in #1004. However, when the type of input data for DCN is float32, the bug still exists. The same bug also exits in DCNv2.
Here is I'd like to do:
- Fixes the bugs whether the input type is float16 or float32, when using amp.
- Add amp unit tests for DCN/DCNv2 ops.
- Cast the type of DCN/DCNv2 _weight_ and _input_ manually according to the type of _offset_. 
The _offset_ in deform_conv is computed by a Conv2d which supports amp, so the type of _offset_ is the flag for whether we use fp16 or amp.
- Add amp unit tests for DCN/DCNv2 ops. 
With amp (pytorch >= 1.6.0), the model type will not be set manually. The …
=> [Fix] Support amp (pytorch >= 1.6.0) on DCN and DCNv2/ Add unit tests on DCN/DCNv2 amp

docs/tensorrt_custom_ops.md, docs/tensorrt_plugin.md, mmcv/ops/csrc/tensorrt/plugins/trt_cummaxmin.cpp, mmcv/ops/csrc/tensorrt/plugins/trt_cummaxmin_kernel.cu, mmcv/ops/csrc/tensorrt/plugins/trt_plugin.cpp, mmcv/ops/csrc/tensorrt/trt_cummaxmin.hpp, mmcv/tensorrt/tensorrt_utils.py, tests/test_ops/test_tensorrt.py
Hi,
This PR adds cummax/cummin support to TensorRT.
=> [Feature] add cummax/cummin tensorrt plugin

mmcv/cnn/utils/weight_init.py, tests/test_cnn/test_weight_init.py
Previous ``INITIALIZERS`` only initialize the class in  ``layer`` of  ``init_cfg``. However, there is a requirement to initialize derived classes from a base class like ``_ConvNd``, ``_BatchNorm``. This pr is for matching the name of the base class, and we can specify the ``layer`` of ``init_cfg`` as the base names and initialize its derived classes.  
1. Add ``_get_bases_name`` in mmcv/cnn/utils/weight_init.py.
2. Revise initializers to determine whether base name or class name is in ``layer`` of ``init_cfg``.
3. Add related unit tests.
=> [Features] Support name of the base classe matching in init_cfg

mmcv/fileio/parse.py
* The default encoding in some windows machine is `'cp936'`, etc. We surely want utf-8.
* Remove \r in windows.
=> Imporve windows support for list_from_file

mmcv/runner/base_runner.py, mmcv/runner/fp16_utils.py, mmcv/runner/hooks/optimizer.py
Sometimes the resumed fp16 training produces wired behaviors because the current fp16 training process does not save `Fp16OptimizerHook.loss_scaler` state to the checkpoint file. 
Hence in this PR, we enable resuming fp16 training by saving and loading fp16 related hook states.
Basically, to enable resume in fp16 training, we add the following steps:
1. Save loss_scaler state_dict: at each iteration, the OptimizerHook will save its loss_scaler's state_dict to runner.meta;
2. At save time, CheckpointHook will write the recorded …
=> Support resume for fp16 training

mmcv/runner/hooks/logger/text.py
I need this in a subclass, but I dont want copy the whole `log()` function
=> add a return value in TextLoggerHook.log()

mmcv/cnn/bricks/transformer.py, tests/test_cnn/test_transformer.py
This PR can solve the BC-breaking of importing the MultiScaleDeformableAttention from ``mmcv.cnn.bricks.transformer``.
Add a dummy module to raise the ImportError when exactly using the module instead of when importing it.
=> Avoid bc-breaking of importing `MultiScaleDeformableAttention`

mmcv/cnn/utils/weight_init.py
+ The warning is designed to remind users that at least one of  ``layer`` and  ``override`` must have values, but it reports incorrectly when users use ``override`` key. I delete it in this PR to avoid confusing users.
+ Delete the warning report in mmcv/mmcv/cnn/utils/weight_init.py
=> [Fix] Delete incorrect warning report when weights initialization

mmcv/utils/__init__.py, mmcv/utils/misc.py, tests/test_utils/test_misc.py
=> [Enhancement] Add to_ntuple

mmcv/ops/csrc/tensorrt/plugins/trt_modulated_deform_conv.cpp
A bug was found while testing modulated deformconv batch inference.
- Must use inputs[3].d[0] instead of inputs.[2].d[0]
=> Fix the dimension

mmcv/ops/csrc/parrots/bbox_overlaps_parrots.cpp, mmcv/ops/csrc/parrots/carafe_naive_parrots.cpp, mmcv/ops/csrc/parrots/carafe_parrots.cpp, mmcv/ops/csrc/parrots/cc_attention_parrots.cpp, mmcv/ops/csrc/parrots/deform_conv_parrots.cpp, mmcv/ops/csrc/parrots/deform_roi_pool_parrots.cpp, mmcv/ops/csrc/parrots/focal_loss_parrots.cpp, mmcv/ops/csrc/parrots/masked_conv2d_parrots.cpp, mmcv/ops/csrc/parrots/modulated_deform_conv_parrots.cpp, mmcv/ops/csrc/parrots/sync_bn_parrots.cpp, mmcv/ops/csrc/parrots/tin_shift_parrots.cpp
Fix compile error in parrots when no cuda
=> [Fix] Fix parrots cpu compile bug

mmcv/image/__init__.py, mmcv/image/geometric.py, tests/test_image/test_geometric.py
To meet the requirement of some networks that the size of the input image should be multiple to the divisor
Add `divisor` argument to `imresize` and `imrescale` in `mmcv.image`.
This argument rounds up the resized or rescaled image size to the nearest value that can be divisible by the divisor.
=> [Enhancement] Support resize or rescale to multiple

mmcv/utils/config.py
To fix the permission denied error when using '--resuming-from' on Windows.  [[#1063](https://github.com/open-mmlab/mmcv/issues/1063)] [[#4966(mmdet)](https://github.com/open-mmlab/mmdetection/issues/4966)]
I'm not sure whether that modification will cause any problems on other platforms or not, so I add an 'if' to ensure Windows only.
Modify the behavior of loading config on Windows:
* Temporary file now will be closed without being deleted before reading on Windows.
* When read ends, it will be deleted by `os.unlink`.
1. …
=> [Fix] Fix the permission denied error on windows.

mmcv/cnn/bricks/activation.py, mmcv/ops/saconv.py, mmcv/parallel/distributed.py, mmcv/parallel/distributed_deprecated.py, mmcv/runner/dist_utils.py, mmcv/runner/fp16_utils.py, mmcv/runner/hooks/logger/tensorboard.py, mmcv/runner/hooks/optimizer.py, tests/test_ops/test_deform_conv.py, tests/test_ops/test_modulated_deform_conv.py
Origin version checking compares 2 strings, which leads to bugs like '0.8.0' > '0.10.0'
Use LooseVersion for Version Checking.
=> [Fix] use LooseVersion for version checking

mmcv/ops/saconv.py
Fix SAConv forward, be compatible with torch1.9.0
Add zero_bias in the arguments of _conv_forward
=> [Fix] Fix saconv

mmcv/model_zoo/open_mmlab.json
Add MobileNetV2 pretrained weight converted from [here](https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth) because MobileNetV2 in MMDetection has different parameter keys from MMClassification.
Requested by https://github.com/open-mmlab/mmdetection/issues/5495
Related to https://github.com/open-mmlab/mmclassification/issues/246
=> Add MobileNetV2 pretrained weight for MMDetection

mmcv/ops/csrc/tensorrt/plugins/trt_corner_pool.cpp, mmcv/ops/csrc/tensorrt/plugins/trt_corner_pool_kernel.cu, mmcv/ops/csrc/tensorrt/plugins/trt_plugin.cpp, mmcv/ops/csrc/tensorrt/trt_corner_pool.hpp, tests/test_ops/test_tensorrt.py
Support tensorrt custom plugin `MMCVCornerPool`, aligned with previous customized onnxruntime operation [`mmcv::MMCVCornerPool`](https://github.com/open-mmlab/mmcv/pull/997).
=> Support tensorrt custom plugin `MMCVCornerPool`

mmcv/runner/iter_based_runner.py
`IterBasedRunner` doesn't support custom hooks by now.
Support custom hooks in `IterBasedRunner`.
No
Refers to https://github.com/open-mmlab/mmcv/pull/1120
=> [Feature] Support custom hooks in `IterBasedRunner`.

.github/workflows/build.yml, mmcv/utils/__init__.py, mmcv/utils/trace.py, tests/test_utils/test_trace.py
Head needs different behaviors in test and export, so we need to use `torch.jit.is_tracing` to judge different situations.
But `torch.jit.is_tracing` has a bug in PyTorch 1.6.0, so we need a wrapper to support trace judgement.
Add a helper function in `mmcv/utils`, and add unit tests.
No
```python
import torch
from mmcv.utils import is_tracing
def foo(x):
if is_tracing():
return x
else:
return x.tolist()
>>> x = torch.ones(3)
>>> foo(x)
[1.0, 1.0, 1.0]
>>> traced_foo = torch.jit.trace(foo, (torch.rand(1), ))
>>> traced_foo(x)
tensor([1., 1., 1.])
```
=> [Feature] Add `is_tracing` to wrap `torch.jit.is_tracing` in different versions.

mmcv/image/photometric.py, tests/test_image/test_photometric.py
`imequalize` in mmcv have a potential integer overflow bug and get result like the following image:
While in Pillow, it's right.
Conver all numbers in `lut` greater than 255 to 255.
No
=> [Fix] Fix potential interger overflow in `imequalize`.

mmcv/onnx/symbolic.py, tests/test_ops/test_onnx.py
This PR add ONNX export support to `torch.roll`. 
Related to https://github.com/open-mmlab/mmsegmentation/issues/693#issuecomment-878057857
Add `torch.roll` symbolic file and related onnx test.
=> [Feature] Add ONNX export support to torch.roll

mmcv/ops/upfirdn2d.py
The StyleGAN2-ADA method needs a more general interface for the `upfirdn2d` function.
Just modify the interface of the `upfirdn2d` function to support more data types.
No.
=> [Enhancement] Revise the interface of upfirdn2d function

mmcv/runner/hooks/lr_updater.py, tests/test_runner/test_hooks.py
In some cases we want to anneal lr after a 'flat lr' period. 
Add a flat + cosine annealing lr scheduler similar to https://github.com/fastai/fastai/blob/master/fastai/callback/schedule.py#L128.
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If this PR introduces a new feature, it is better to list some use cases here, and update …
=> [Feature] Add flat cosine lr updater

mmcv/utils/logging.py
The console handler present in the root logger leads to duplicate messages being printed on the console, creating unnecessary clutter. This has also been discussed [here](https://discuss.pytorch.org/t/distributed-1-8-0-logging-twice-in-a-single-process-same-code-works-properly-in-1-7-0/114103/6). This PR fixes this issue, and resolves #1000. 
In `mmcv.utils.get_logger()`, all `StreamHandler` present in the root logger are set to log at the `ERROR` level, instead of `NOTSET` which is the default.
=> Resolves the duplicate logs issue

mmcv/ops/carafe.py
When training fpn_carafe neck in mmdet with feature of dtype torch.half, the execution fails with:
_RuntimeError: expected scalar type Half but found Float_
at mmcv/ops/carafe.py l130
The code works with features of dtype torch.float
The issue arise from  mismatch in dtype between features and masks. This difference is created in the 'kernel_normalizer' function (carafe.py l263) where F.softmax returns by default results of dtype torch.float.
By setting the dtype argument to mask.dtype, F.softmax forwards the correct dtype.
No
=> Prevent kernel_normalizer to change mask dtype

.github/workflows/build.yml, .github/workflows/publish-to-pypi.yml
Related Issue: #1219
Related Action: https://github.com/open-mmlab/mmcv/runs/3150536246?check_suite_focus=true#step:4:17
Fix CI of publishing package
- .github/workflows/build.yml
- .github/workflows/publish-to-pypi.yml
If this PR introduces a new feature, it is better to list some …
=> [Fix] Fix CI of publishing package

mmcv/ops/csrc/parrots/deform_conv_cuda.cu, mmcv/ops/csrc/pytorch/deform_conv_cuda.cu
resolve: #1169 
This PR should be merged after the parrot's operation being tested by the code segment below.
```
from mmcv.ops import DeformConv2dPack
import torch
input_tensor = torch.rand(128, 64, 100, 100)
input_tensor.requires_grad_(True)
input_tensor = input_tensor.cuda()
dcn = DeformConv2dPack(64, 64, 3, ).cuda()
out = dcn(input_tensor).sum()
out.backward()
```
=> fix dcn forward and backward when batchsize is larger than im2col_step

mmcv/ops/carafe.py, mmcv/ops/cc_attention.py, mmcv/ops/deform_roi_pool.py, mmcv/ops/focal_loss.py, mmcv/ops/masked_conv.py, mmcv/ops/psa_mask.py, mmcv/ops/sync_bn.py
Custom ops can not be exported to onnx unless the node is in a non-default namespace. This PR adds namespace `mmcv` to the custom ops so they can be exported.
Note that the converted node might not be used in some backend until the implementation of the backend is added.
Add `mmcv` namespace to custom ops, fix data type of the attributes.
=> [Enhance] Add onnx namespace for custom ops

docs/community.rst, docs_zh_CN/_static, docs_zh_CN/community.rst, docs_zh_CN/community/pr.md, docs_zh_CN/conf.py, docs_zh_CN/understand_mmcv/data_process.md, mmcv/image/photometric.py, mmcv/runner/hooks/evaluation.py
Remove the `_static` directory in docs_zh_CN because it is a symbolic link of `mmcv/docs/_static` and a symbolic link can not be shown in Github.
- Before the PR
https://github.com/open-mmlab/mmcv/blob/v1.3.11/docs_zh_CN/community/pr.md
- After the PR
https://github.com/zhouzaida/mmcv/blob/fix-docs/docs_zh_CN/community/pr.md
https://mmcv-pr1277.readthedocs.io/en/latest/community/pr.html
- Delete `_static `in docs_zh_CN
- Replace `../_static` with `../../docs/_static`
- Fix sphinx warning like indent error
Does the modification …
=> [Docs] Remove the _static in docs_zh_CN

mmcv/ops/csrc/onnxruntime/cpu/nms.cpp, mmcv/ops/csrc/parrots/nms.cpp, mmcv/ops/csrc/pytorch/nms.cpp
I found the implementations of nms op are different betweed cpu and gpu. This PR is to fix it.
Modify the condition `I / U >= iou_threahold`  to `I / U > iou_threahold`.
1. …
=> fix nms implentation of cpu

docs/understand_mmcv/config.md, mmcv/utils/config.py, tests/data/config/deprecated.py, tests/data/config/deprecated_as_base.py, tests/data/config/expected.py, tests/test_utils/test_config.py
Support deprecation information in Config. Users can add a field `_deprecation_` into a config file, which will trigger a deprecation warning during calling `Config.fromfile`. Optionally, the warning information can include a path to the expected config file to replace the deprecated one.
- Add deprecation information support in `config.py`
- Add unittest
For example, if a config file `old_config.py` has been renamed to `new_config.py`. To avoid bc-breaking, we can create an `old_config.py` file with deprecation information as following:
```python
_base_ = './new_config.py'
_deprecation_ = dict(expected='configs/new_config.py')
```
=> Support deprecation info in Config

.github/pull_request_template.md
This PR updates the PR template.
The checklist in the template has been updated and use check mark for better usage.
N/A
N/A
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or …
=> [Enhance]: update pr template

docs/deployment/onnxruntime_custom_ops.md, mmcv/ops/csrc/onnxruntime/corner_pool.h, mmcv/ops/csrc/onnxruntime/cpu/modulated_deform_conv.cpp, mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp, mmcv/ops/csrc/onnxruntime/modulated_deform_conv.h, mmcv/ops/csrc/onnxruntime/reduce_ops.h, mmcv/ops/csrc/onnxruntime/roi_align.h, mmcv/ops/csrc/onnxruntime/roi_align_rotated.h, mmcv/ops/csrc/onnxruntime/soft_nms.h, tests/test_ops/test_onnx.py
Run some model in mmocr (e.g. dbnet) using onnxruntime.
Following the the mmcv guide, add `modulated_deform_conv.cpp`, `modulated_deform_conv.h`  and `test_onnx.py`.
The modulated_deform_conv op definition is following [mmcv-tensorrt-custom-op](https://github.com/open-mmlab/mmcv/blob/master/docs/deployment/tensorrt_custom_ops.md#mmcvmodulateddeformconv2d)
Because the input `bias` is optional and there are parameters in the type of `list of ints`, like `stride`, the onnxruntime needs to upgrade to 1.8.0+.  For myself, I use onnxruntime-1.8.1. Comparing to the onnxruntime-1.5.1, which is given in mmcv official guild, some function definitions are changed. Thus I also make some modifications in other custom op definations.
=> add modulated_deform_conv in onnxruntime support

mmcv/onnx/info.py, mmcv/ops/csrc/parrots/sync_bn_parrots.cpp
Fix sync_bn bug in parrots. And when use parrots, open custom op exporting.
=> fix parrots op bug

mmcv/runner/checkpoint.py, tests/test_runner/test_checkpoint.py
PyTorch provides `_version` in `nn.Module` to support backward compatibility. However, because of some modifications in saving & loading in mmcv, when overriding the `_load_from_state_dict` in a module, the `local_metadata` is empty dict now.
Modify some code in saving and loading to keep `state_dict._metadata`.
No, it should be beneficial for backward compatibility, because downstream repos, like `mmdet`, are using these metadata to support old version checkpoints, and this function is not available now.
```python
>>> import torch
>>> import torch.nn as nn
>>> from mmcv.runner import save_checkpoint
>>> 
>>> class ModelV2(nn.Module):
...     _version = 2
... 
...     def __init__(self):
...         super().__init__()
...         self.conv = nn.Conv2d(3, 3, 1)
...
>>> …
```
=> [Fix] Fix missing `state_dict._metadata` when saving and loading checkpoints.

docs_zh_CN/faq.md
Translation of docs/faq.md
docs_zh_CN/faq.md
=> translation of faq.md

docs_zh_CN/understand_mmcv/ops.md
Translate `docs/understand_mmcv/ops.md`
Add `docs_zh_CN/understand_mmcv/ops.md`
**Before PR**:
**After PR**:
=> [Docs] Translate ops documentation

docs/understand_mmcv/cnn.md, docs_zh_CN/understand_mmcv/cnn.md
Document translation
Modified:  docs_zh_CN/understand_mmcv/cnn.md
None
None
=> [Docs] cnn.md translated

mmcv/ops/csrc/pytorch/correlation.cpp
There are some unrecognized symbols when compiling correlation op on Windows platform.
1. Revise `and` to `&&`
No
**Before PR**:
**After PR**:
=> [Fix] Unrecognized symbol in correlation.cpp

mmcv/runner/dist_utils.py
Due to our lowest supported PyTorch is 1.3.0, I remove the condition to check whether PyTorch version is lower than 1.0 in  `get_dist_info()` 
modify `get_dist_info()`
No
**Before PR**:
**After PR**:
=> [Refactor] Remove some outdated lines

mmcv/utils/path.py, tests/test_utils/test_path.py
Some file suffixs are case-insensitive, such as ".JPG" and ".jpg", so add `case_sensitive` option in scandir. Default True, behave as before. 
For example, `scandir(root, suffix='JPG', case_sensitive=False)` can find pictures with  suffix of both ".JPG" and ".jpg" , while`scandir(root, suffix='JPG')` can  only find pictures with suffix of ".JPG" .
Add case_sensitive option in scandir. Default True, behave as before.
if set  case_sensitive to False, ignore the case of suffix.
No.
**Before PR**:
**After PR**:
=> Add case case_sensitive in scandir

mmcv/cnn/bricks/transformer.py, tests/test_cnn/test_transformer.py
Fixes the wrong function/weight reference bug in BaseTransformerLayer when `batch_first` is True.
There are some cases that users clone a model with `copy.deepcopy` to create, for example, a `ModuleList`. However, things become tricky when it comes to `BaseTransformerLayer`. If we create a ModuleList on GPU in this way with `batch_first=True` and run the forward function, an error will prompt saying the weights are not on GPU.
```python
baselayer = BaseTransformerLayer(
operation_order=('self_attn', 'ffn'),
batch_first=True,
attn_cfgs=dict(
type='MultiheadAttention',
embed_dims=256,
num_heads=8,
),
)
baselayers = ModuleList([copy.deepcopy(baselayer) for _ in range(2)])
baselayers.to('cuda')
x = torch.rand(2, 10, 256).cuda()
out = baselayers[0](x)
```
The error:
```
RuntimeError: Tensor …
```
=> [Fix] fix the wrong weight reference bug in BaseTransformerLayer 

mmcv/ops/correlation.py, mmcv/ops/group_points.py, mmcv/ops/points_sampler.py
There exits some invalid symbols in docstring, and raise exception when compiling documents with latex 
1. revise the docstring in mmcv/ops/correlation.py
2. revise the docstring in mmcv/ops/group_points.py
3. revise the docstring in mmcv/ops/points_sampler.py
No
No
**Before PR**:
**After PR**:
=> [Doc] Fix invalid symbols in docstring

mmcv/runner/hooks/evaluation.py, tests/test_runner/test_eval_hook.py
Related Issue: https://github.com/open-mmlab/mmdetection/issues/6265
Raise AssertionError when `eval_res` returned by `dataset.evaluate()` is a null `dict` which may occur when training loss is nan.
https://github.com/open-mmlab/mmcv/blob/f22c9eb4a409470b7e645f17fa1997fe85e27909/mmcv/runner/hooks/evaluation.py#L317-L336
Add an Assert clause to check whether `eval_res` is a null `dict`
If so, please describe how it breaks …
=> [Fix] Print a warning log when eval_res is an empty dict

mmcv/runner/checkpoint.py
I'm using mmcv within another codebase and i have issues with loading a checkpoint from http in multi-GPU setting. 
Specifically i get the error: 
```
File "/mmcv/runner/checkpoint.py", line 290, in load_from_http
return checkpoint
UnboundLocalError: local variable 'checkpoint' referenced before assignment
```
This is because get_dist_info does not correctly get world_size in L280, but rank is correctly inferred via L281. Hence, the variable checkpoint will not be defined on return (rank > 0 but world_size == 1).
I can mitigate the problem by modifying this line:
https://github.com/open-mmlab/mmcv/blob/f22c9eb4a409470b7e645f17fa1997fe85e27909/mmcv/runner/checkpoint.py#L282
to 
`if rank == 0 or world_size == 1:`
=> add world_size in if clause in load_from_http

mmcv/ops/csrc/common/mlu/roi_align_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/roi_align_mlu.cpp, mmcv/ops/csrc/pytorch/roi_align.cpp, tests/test_ops/test_roi_align.py
The motivation of the PR is to support running RoiAlign with Cambricon MLU backend.
Refactor roi_align.cpp and roi_align_backward.cpp to support dispatching to MLU.
Add roi_align.cpp, roi_align_backward.cpp, roi_align_internal. mlu, roi_align_backward_internal.mlu cpp and bang src code.
Refactor test_roi_align.py to support testing roi_align with MLU backend.
Does the modification introduce changes that break the backward-compatibility of the …
=> [Feature] Support RoiAlign With Cambricon MLU Backend

mmcv/ops/csrc/common/mlu/bbox_overlaps_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/bbox_overlaps.cpp, mmcv/ops/csrc/pytorch/mlu/bbox_overlaps_mlu.cpp, tests/test_ops/test_bbox.py
The motivation of the PR is to support running BBoxOverlaps with Cambricon MLU backend.
Add bbox_overlaps_mlu_kernel.mlu src code as mlu kernel.
Add bbox_overlaps_mlu.cpp and refactor bbox_overlaps.cpp to support dispatching to MLU in pytorch.
Refactor test_bbox.py to support testing bbox_overlaps with MLU backend.
MLU src code
Add MLU src code of bbox_overlaps in directory mmcv/ops/csrc/common/mlu/bbox_overlaps_mlu_kernel.mlu.
Dispatch
Add dispatching to BBoxOverlapsMLUKernelLauncher in …
=> [Feature] Support BBoxOverlaps with cambricon MLU backend

docs/understand_mmcv/registry.md
The grammatical error of mmcv registry doc
be find here —> be found here
None
=> [Doc]: Fix grammatical error

examples/train.py, mmcv/parallel/data_parallel.py
Related issue: https://github.com/open-mmlab/mmcv/issues/1470.
Some users want to test the example/train.py on single GPU even though there are multiple GPUs on their machines.
Force to use GPU:0 can avoid Error traceback.
Assign `device_ids = [0]` and fix a format error by the way.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
=> [Fix] fix train example

mmcv/ops/csrc/common/cuda/scatter_points_cuda_kernel.cuh
Related issue #1435 
Fix compiled error on windows due to the invalid preprocessor command 'warning'
- mmcv/ops/csrc/common/cuda/scatter_points_cuda_kernel.cuh
No
**Before PR**:
**After PR**:
=> [Fix] Fix compiled error on windows

mmcv/ops/csrc/pytorch/pybind.cpp
`iou3d_nms_forward` and `iou3d_nms_normal_forward` have different function declaration between `pybind.cpp` and `iou3d.cpp`.
Remove return value of `iou3d_nms_forward` and `iou3d_nms_normal_forward`.
=> [Fix] Fix iou3d python bind

setup.py
Fix the compiled error on windows due to the c++14 flag.
**Compiled error on Windows**
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/include\xutility(1326): error: expected a "("
detected during:
instantiation of "decltype(auto) std::_Get_unwrapped(_Iter &&) [with _Iter=const uint64_t *const &]"
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/include\xutility(1326)
```cpp
template <class _Iter>
_NODISCARD constexpr decltype(auto) …
```
=> [Fix] Fix the compiled error on windows due to the c++14 flag

mmcv/ops/csrc/common/cuda/correlation_cuda.cuh, mmcv/ops/csrc/common/pytorch_device_registry.hpp
Can not build mmcv-full with cuda9.0.
Reference
https://github.com/pytorch/extension-cpp/issues/35
Replace `torch/extension.h` with `torch/types.h`
=> [Fix] Fix build with cuda9.0

MANIFEST.in
Install from pip failed because `mmcv/ops/csrc/pytorch/cpu/*.cpp` and `mmcv/ops/csrc/pytorch/cuda/*.cpp` has not been added.
Add `mmcv/ops/csrc/pytorch/cuda/*.cpp` and `mmcv/ops/csrc/pytorch/cpu/*.cpp` in `MANIFEST.in`
=> [Fix] Fix install from pip

docs/deployment/mmcv_ops_definition.md, docs/deployment/onnx.md, docs/deployment/onnxruntime_custom_ops.md, docs/deployment/onnxruntime_op.md, docs/deployment/tensorrt_plugin.md, docs/index.rst
Origanization of documents for deployment in mmcv is a bit mess, could refer to [readthedocs](https://mmcv.readthedocs.io/en/latest/)
Reorganize docs in deployment and fix some bad formats.
None
=> [Doc]: Fix deploy doc

mmcv/runner/hooks/optimizer.py, tests/test_runner/test_hooks.py
Sometimes there are some anomalous parameters in the training phase, mainly two cases 
- Some parameters are  not be used in a forward pass due to our wrong implementation, which causes the error when doing `loss.backward()`
- Some parameters are not be used to produce loss, which causes the deadlock when doing `loss.backward()`
In both cases，anomalous parameters are not included in the computational graph that is with `loss` as the root.
I add a debug option named `detect_anomalous_params`  to `OptimizerHook`, which can help you find anomalous parameters  
None
=> [Feature] Detect anomalous parameters

mmcv/ops/csrc/common/mlu/focal_loss_sigmoid_mlu_kernel.mlu, mmcv/ops/csrc/common/mlu/nms_mlu_kernel.mlu, mmcv/ops/csrc/common/mlu/roi_align_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/focal_loss.cpp, mmcv/ops/csrc/pytorch/mlu/focal_loss_sigmoid_mlu.cpp, mmcv/ops/csrc/pytorch/mlu/nms_mlu.cpp, mmcv/ops/csrc/pytorch/roi_align.cpp
Improve the performance of roialign_forward, roialign_backward, nms and focalloss_forward with MLU backend.
1. Add an optimized kernel BinPart for roialign_forward in `mmcv/ops/csrc/common/mlu/roi_align_mlu_kernel.mlu`.
2. Change the partition strategy over onchip resources for roialign_backward in `mmcv/ops/csrc/common/mlu/roi_align_mlu_kernel.mlu`.
3. Add unionX kernel for nms in `mmcv/ops/csrc/common/mlu/nms_mlu_kernel.mlu` and `mmcv/ops/csrc/pytorch/mlu/nms_mlu.cpp`.
4. Change the computation strategy of …
=> [Improve] Improve the perf of roialign, nms and focalloss with MLU backend

mmcv/ops/csrc/common/cuda/riroi_align_rotated_cuda_kernel.cuh, mmcv/ops/csrc/common/cuda/voxelization_cuda_kernel.cuh
Compilation errors in CUDA kernels on floor() calls. Type mismatch, floorf must be used for float.
Replace floor() by floorf().
Windows 10
Visual Studio Community 2019 (v16.9.4)
MSVC++ 14.28
CUDA 11.1
**Before PR**:
**After PR**:
=> Fix Windows cuda compilation error on floor()

mmcv/ops/box_iou_rotated.py, mmcv/ops/nms.py, tests/test_ops/test_box_iou_rotated.py, tests/test_ops/test_nms_rotated.py
- add `clockwise` argument to ops `box_iou_rotated` and `nms_rotated`
- add docstrings to clarify the coordination systems used for the representation of rotated bounding boxes
=> [Enhancement] Add clockwise argument to ops box_iou_rotated and nms_rotated

README.md, README_zh-CN.md, docs/en/get_started/introduction.md, docs/zh_cn/get_started/introduction.md
Add the link of mmdeploy.
- README.md
- docs/en/get_started/introduction.md
- docs/zh_cn/get_started/introduction.md
**Before PR**:
**After PR**:
=> [Docs] Add the link of mmdeploy

mmcv/runner/hooks/logger/wandb.py, tests/test_runner/test_hooks.py
**Problem:** Currently it is not possible to upload experiment config files and model weights to wandb. However it very crucial to properly track experiments.
**Solution:** With this PR, users can upload the contents in `work_dir` to wandb after training ends utilizing `log_artifact()` method of wandb logger: https://docs.wandb.ai/ref/python/run#log_artifact
**Usage:**
```python
log_config = dict(
interval=1,
hooks=[
dict(
type="WandbLoggerHook",
init_kwargs=dict(
entity=WANDB_ENTITY,
project=WANDB_PROJECT,
name=WANDB_NAME,
),
log_artifact=True,
out_suffix=('.log.json', '.log', '.py', '.pt')
),
],
)
```
=> add artifact logging to wandb hook

mmcv/ops/csrc/pytorch/cuda/active_rotated_filter_cuda.cu
Fix a bug in the op `active_rotated_filter`. The buggy code incurs "CUDA illegal memory access" and `nan` loss after training s2anet for several iterations.
=> [Fix] fix a bug of CUDA illegal mem access when training s2anet

mmcv/cnn/bricks/hsigmoid.py, requirements/test.txt, tests/test_cnn/test_hsigmoid.py
Align `HSigmoid` with pytorch official.
PyTorch `Hardsigmoid` is provided from 1.6.0 and does not support `bias`, `divisor`, `min_value`, `max_value` args.
mmcv/cnn/bricks/hsigmoid.py
tests/test_cnn/test_hsigmoid.py
Yes. Downstream projects could keep compatibility with this PR by modifying the args of `HSigmoid`.
**Before PR**:
**After PR**:
=> [Fix] Align HSigmoid with pytorch official

mmcv/runner/hooks/logger/mlflow.py, tests/test_runner/test_hooks.py
https://github.com/mlflow/mlflow/issues/4903
Mlflow logger throws an error when saving the pytorch model due to mismatch between torch version and mlflow's torch version interpretation.
Followed the suggestion. https://github.com/mlflow/mlflow/issues/4903#issuecomment-944342775
https://mlflow.org/docs/latest/python_api/mlflow.pytorch.html#mlflow.pytorch.log_model
=> [Fix] mlflow logger error

mmcv/ops/nms.py, tests/test_ops/test_nms_rotated.py
Currently, `batched_nms` does not work appropriately when nms_type is set to 'nms_rotated'.
```
if boxes_for_nms.shape[0] < split_thr or torch.onnx.is_in_onnx_export():
dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
boxes = boxes[keep]
scores = dets[:, 4]
```
This is due to fixed indexing for scores.
I added a conditional variable to determine the index of scores.
`nms_match` cannot be evaluated with batched_nms, too.
Should we add assertion for nms_type?
=> [Fix] batched nms for nms_rotated

mmcv/utils/config.py, tests/test_utils/test_config.py
The original `Config` doesn't support deep copy because it will call the `__deepcopy__` method of `ConfigDict`.
Add `__deepcopy__` to `Config`.
No
- Before the PR
```python
>>> from mmcv import Config
>>> from copy import deepcopy
>>> cfg = Config.fromfile("./tests/data/config/a.py")
>>> new_cfg = deepcopy(cfg)
>>> type(cfg) == type(new_cfg)
False
>>> type(cfg), type(new_cfg)
(mmcv.utils.config.Config, mmcv.utils.config.ConfigDict)
```
- After the PR
```python
>>> from mmcv import Config
>>> from copy import deepcopy
>>> cfg = Config.fromfile("./tests/data/config/a.py")
>>> new_cfg = deepcopy(cfg)
>>> type(cfg) == type(new_cfg)
True
>>> type(cfg), type(new_cfg)
(mmcv.utils.config.Config, mmcv.utils.config.Config)
>>> print(cfg._cfg_dict == new_cfg._cfg_dict)
True
>>> print(cfg._cfg_dict …
```
=> Support deepcopy for Config

mmcv/ops/csrc/common/cuda/roi_align_rotated_cuda_kernel.cuh, mmcv/ops/csrc/parrots/roi_align_rotated_parrots.cpp, mmcv/ops/csrc/parrots/roi_align_rotated_pytorch.h, mmcv/ops/csrc/pytorch/cpu/roi_align_rotated.cpp, mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/cuda/roi_align_rotated_cuda.cu, mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/csrc/pytorch/roi_align_rotated.cpp, mmcv/ops/roi_align_rotated.py, tests/test_ops/test_roi_align_rotated.py
RoIAlignRotated does not have the same interface as RoIAlign.
I edited its interface and added deprecated warning.
=> [Refactor] Refactor the interface for RoIAlignRotated

docs/en/deployment/onnx.md, docs/en/deployment/onnxruntime_op.md, docs/en/deployment/tensorrt_plugin.md, mmcv/onnx/info.py, mmcv/onnx/symbolic.py, mmcv/tensorrt/init_plugins.py, mmcv/tensorrt/preprocess.py, mmcv/tensorrt/tensorrt_utils.py, setup.py
This PR add deprecate warning to codes about model deployment.
Add warning in codes and docs.
Codes include c++ and cuda ops implement will be deprecated in the future.
=> deprecate model deployment

mmcv/transforms/processing.py, tests/test_transforms/test_transforms_processing.py
When using `Pad` to pad image, we support the type of pad_val is int or dict. If the type of pad_val is int, `Pad` should pad all the channels of the image with pad_val. The pad_val should have the same dim with an image.
=> [Fix] Pad boader fix

mmcv/cnn/bricks/conv.py
Fix typo in conv.py.
Fix typo.
Modified "Unrecognized norm type" -> "Unrecognized layer type" in [this line](https://github.com/open-mmlab/mmcv/blob/fd3a1a16ea1d0b3def8719816007a5d6fd6b432e/mmcv/cnn/bricks/conv.py#L38).
If this PR introduces a new feature, it is better to …
=> fix typo in conv.py

mmcv/ops/csrc/pytorch/cuda/scatter_points_cuda.cu, tests/test_ops/test_scatter_points.py
The unittest of mmdet3d fails after importing the DynamicScatter op from mmcv. I found that there exists an inconsistency of DynamicScatter op between mmdet3d and mmcv, which causes the failure of mmdet3d.
Recover the `if` statement.
If this PR introduces a new feature, it is …
=> [Fix] Fix bugs in DynamicScatter op

mmcv/ops/csrc/common/cuda/voxelization_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cpu/voxelization.cpp
The unittest of mmdet3d fails after importing the Voxeliaztion op from mmcv. I found that there exists an inconsistency of Voxelization op between mmdet3d and mmcv, which causes the failure of mmdet3d.
Replace `memcpy` with loop in the Voxelization op.
If this PR introduces a …
=> [Fix] Fix bugs in Voxelization op

mmcv/runner/optimizer/default_constructor.py
Ex.2 in the docstring of `DefaultOptimizerConstructor` seems to be wrong. The `backbone` module cannot be matched by `.backbone`.
=> [Docs] Fix a wrong example in `DefaultOptimizerConstructor`

docs/en/understand_mmcv/cnn.md
Making the docs error-proof.
Fixed typo in `docs/en/understand_mmcv/cnn.md`. The `BaseModule` class implements `init_weights()` not `init_weight()`
**Before PR**:
**After PR**:
=> Fixed typo in docs/en/understand_mmcv/cnn.md

.github/workflows/build.yml, tests/test_parallel.py
Add PyTorch1.11.0 CI.
As above.
**Before PR**:
**After PR**:
=> [Enhancement] Add PyTorch1.11.0 CI

mmcv/transforms/utils.py, mmcv/transforms/wrappers.py, tests/test_transforms/test_transforms_wrapper.py
In `RandomChoice` the selected index of sub-pipeline candidates is randomly generated, thus should be decorated by `cacheable_method`.
- RandomChoice uses cacheable_method to generate pipeline index
- RandomChoice add `__iter__()`
- Fix incorrect use of cacheable_method in unit tests.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
=> [Fix] Add @cacheable_method in transform wrapper `RandomChoice`

setup.py, tests/test_ops/test_onnx.py
MMCV ops building failed on rocm pytorch.
Update the setup.py script.
Note that some test might failed with log:
```
MIOpen(HIP): Warning [ForwardBackwardDataGetWorkSpaceSizeWinograd] /MIOpen/src/sqlite_db.cpp:108: open memvfs: unable to open database file
MIOpen(HIP): Warning [ForwardBackwardGetWorkSpaceSizeImplicitGemm] /MIOpen/src/sqlite_db.cpp:108: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindWinogradSolutions] /MIOpen/src/sqlite_db.cpp:108: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataDirectSolutions] /MIOpen/src/sqlite_db.cpp:108: open memvfs: unable to open database file
MIOpen(HIP): Warning [FindDataImplicitGemmSolutions] /MIOpen/src/sqlite_db.cpp:108: open memvfs: unable to open database file
MIOpen(HIP): Warning …
```
=> [Fix] Fix rocm support

mmcv/utils/config.py, tests/data/config/l.py, tests/data/config/n.py
When use `import` like `import os.path as osp` in config. The parsed config's `_cfg_dict` contains an entry which looks like `osp: <module ....`. 
Then when calling `pretty_text()`, this dict is converted back to string, which is different from the original config., Then this string is formatted by `yapf` and error occurs. 
```python 
cfg_dict = self._cfg_dict.to_dict()
text = _format_dict(cfg_dict, outest_level=True)
yapf_style = dict(
based_on_style='pep8',
blank_line_before_nested_class_or_def=True,
split_before_expression_after_opening_paren=True)
text, _ = FormatCode(text, style_config=yapf_style, verify=True)
```
When parsing a config file to dict, modules and functions are ignored. 
No
**Before PR**:
**After PR**:
=> [fix] config ignore imported modules and functions

mmcv/ops/csrc/common/cuda/ms_deform_attn_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cuda/ms_deform_attn_cuda.cu
This PR fixes a bug in ms_deformable_attention. The kernel loop failed because the pointer has been changed.
Create a new pointer to trace the value.
close #1817
=> Fix ms deform attn

mmcv/ops/csrc/common/cuda/voxelization_cuda_kernel.cuh
Hello, when I deploy the `CenterPoint` model in mmdeploy, I find a bug in Voxelization op. In point_to_voxelidx_kernel func, if find invalid points or point num out of the boundary, func  `return` will make the following point not processed, and then affect the model results.
Before:
After fix:
=> [Bug] Fix voxelization bug

mmcv/parallel/distributed.py
Fix PyTorch1.11 Dist Remove _sync_params.
As above.
**Before PR**:
**After PR**:
=> [Fix] Fix PyTorch1.11 Dist Remove _sync_params

mmcv/ops/csrc/common/mlu/tin_shift_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/tin_shift_mlu.cpp, mmcv/ops/csrc/pytorch/tin_shift.cpp, mmcv/ops/tin_shift.py, tests/test_ops/test_tin_shift.py
The motivation of the PR is to support running tin_shift forward and backward with Cambricon MLU backend.
It includes four parts:
- Add tin_shift_mlu_kernel.mlu src code as mlu kernel.
- Add tin_shift_mlu.cpp and refactor tin_shift.cpp to support dispatching to MLU in pytorch.
- Refactor test_tin_shift.py to support testing tin_shift with MLU backend.
- Fix the lack of assertion of batch_size in tin_shift.py.
1. MLU source code
- Add MLU src code of tin_shift in directory mmcv/ops/csrc/common/mlu/tin_shift_mlu_kernel.mlu.
2. …
=> [Feature] Support tin_shift with cambricon MLU backend

mmcv/transforms/loading.py, mmcv/transforms/processing.py, tests/test_transforms/test_transforms_loading.py
Fix some typo in transforms according to review. `gt_semantic_seg` -> `gt_seg_map` is changed in #1784
=> [Fix] fix some typo in transforms

docs/zh_cn/understand_mmcv/data_transform.md, mmcv/transforms/__init__.py, mmcv/transforms/loading.py, mmcv/utils/config.py, tests/test_transforms/test_transforms_loading.py
The `LoadAnnotations` is commonly used in mmdet and mmseg, and I missed the tailed "s"
As the title
**Before PR**:
**After PR**:
=> Rename `LoadAnnotation` to `LoadAnnotations`

mmcv/cnn/bricks/conv_module.py
When using GELU in ConvModule, ConvModule raises TypeError: GELU: __init__() got an unexpected keyword argument 'inplace'.
Fix the unexpected keyword bug when using GELU in ConvModule
=> [Fix] GELU got an unexpected keyword argument 'inplace'

.github/workflows/build.yml, requirements/test.txt
Fix Python3.10 CI.
Special treatment for python3.10 because onnxoptimizer and onnxruntime do not support python3.10.
As above
**Before PR**:
**After PR**:
=> [Fix] Fix Python3.10 CI

mmcv/utils/env.py, tests/test_utils/test_env.py
`collect_env()` use `tail` and `head` which is not available on most Windows machines. 
```
'tail' is not recognized as an internal or external command, operable program or batch file.
'head' is not recognized as an internal or external command, operable program or batch file.
```
Remove the `tail` and `head`, and use string find to extract env infos. 
No
**Before PR**:
**After PR**:
=> [Enhancement] Fix collect_env on Windows

mmcv/runner/dist_utils.py
Sometimes torch.distributed default port(29500) is occupied,that's when _init_dist_slurm() need to find a free port.
Add function ``is_port_in_use`` to test if a port is occupied and ``find_free_port`` to find a free port in ``_init_dist_slurm()``
No
No
**Before PR**:
**After PR**:
=> [Feature] Support finding free port in _init_dist_slurm()

mmcv/ops/csrc/common/cuda/correlation_cuda.cuh, mmcv/ops/csrc/pytorch/cuda/correlation_cuda.cu
This PR optmize correlation ops.
Tested on:
Device: RTX 2070super
CUDA: 11.3
nvidia driver: 465.19.01
input size: 2x256x256x256
`num_warmup=10` and `num_tests=100`, `model = Correlation(max_displacement=3)`
| Model        | master         | optmized |
| :----------- | :----------: | :------: |
| forward | 15.46502ms | 9.32997ms |
| forward+backward | 708.94648ms | 198.22428ms |
Note that there are two extra permute(of input) in backward. That means more memory usage.
It will cost us extra ~50ms if we remove the permute tensor.
More test is required.
=> [Enhancment] Optimize correlation

mmcv/utils/registry.py
This PR addresses https://github.com/open-mmlab/mmcv/issues/1843 by improving the performance of
`Registry.__init__()`
Instead of calling inspect.stack() to read the entire stack and its
associated source files from disk, walk up the stack to get only the
specific frame that we need (see [this answer on StackOverflow](https://stackoverflow.com/a/42636264/895769)
for additional information).
This change results in a ~2.5x speed-up when …
=> [Enhancement] Speed up Registry initialization

.github/workflows/build.yml, mmcv/__init__.py, mmcv/device/__init__.py, mmcv/device/mlu/__init__.py, mmcv/device/mlu/_functions.py, mmcv/device/mlu/data_parallel.py, mmcv/device/mlu/distributed.py, mmcv/device/mlu/scatter_gather.py, mmcv/device/mlu/utils.py, mmcv/ops/csrc/common/pytorch_cpp_helper.hpp, mmcv/ops/csrc/common/pytorch_mlu_helper.hpp, mmcv/runner/dist_utils.py, setup.py, tests/test_device/test_mlu/test_mlu_parallel.py
* Support Cambricon MLU device for PyTorch backend.
```setup.py``` is modified to support MLU, with additions of compile with MLUExtensions given by Cambricon PyTorch.
New operators dispatch of "MLU" is ready, and added to ```mlubind.py``` for BangC operators. Src-code will update in the future.
For distributed training, new dist backend named "cncl" is added for MLU.
Since MLU does not support origin ```DataParallel``` and ```DistributedDataParallel```, new modules named ```MLUDataParallel``` and ```MLUDistributedDataParallel``` are supported. They can be used like:
```from mmcv.device.mlu import MLUDataParallel, MLUDistributedDataParallel```.
No BC-breaking.
```
import torch
import torch_mlu
from mmcv.device.mlu import MLUDataParallel, MLUDistributedDataParallel
...
DP_model = …
```
=> [Feature] Support PyTorch backend on MLU

tests/test_ops/test_spconv.py
Some ops unit tests will report errors on circleci, and the main problem is out of memory. So I try to move some op ut to run in sub-threads; when the sub-thread finishes, the sub-thread will release the memory, thus avoiding out of memory.
=> [Fix] Fix spconv unit test by releasing cache on GPU

mmcv/ops/csrc/common/cuda/nms_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cuda/nms_cuda.cu
This PR add a cuda kernel for nms to avoid computation on cpu.
I am not sure if I should call this an "optimization" cause on small input data, cpu performance might even better than gpu. And the data distribution will also affect the performance.
envs:
- Device: RTX 2070super
- CUDA: 11.3
- nvidia driver: 465.19.01
- CPU: Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
Test data comes from [faster rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) and [demo image](https://github.com/open-mmlab/mmdetection/blob/master/demo/demo.jpg). Both nms in rpn and nms in bbox head are tested.
| - | old | new |
| --- | --- | --- |
| rpn data(4741 boxes) | 0.98435ms | **0.88798ms** |
| rcnn data(583 boxes) | 0.23121ms | **0.22827ms** |
| random …
=> NMS with CUDA only

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/__init__.py, mmcv/ops/csrc/common/cuda/diff_iou_rotated_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/cuda/diff_iou_rotated_cuda.cu, mmcv/ops/csrc/pytorch/diff_iou_rotated.cpp, mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/diff_iou_rotated.py, tests/test_ops/test_diff_iou_rotated.py
This PR adds Differentiable rotated IoU both 2d and 3d. It is discusses with @ZwwWayne and @Tai-Wang as a part of work on FCAF3D in mmdetection3d. It also can be used in mmrotate.
Just add a standart cuda op with python wrapper.
No
2d and 3d IoU loss.
=> [Enhance] Differentiable rotated IoU

mmcv/device/mlu/scatter_gather.py
MMDP or MMDDP use origin scatter_gather to scatter Tensor to one or more device(s).
And the result of scatter_map should be a List of Tensor, each item is for one device.
However, the modified scatter_gather for MLUDP or MLUDDP only returns the pure Tensor.
It causes dimension errors when scatter this result again.
Change the output of scatter_map, thus the output is just the same size as GPU or CPU result.
No BC-breaking.
**Before PR**:
**After PR**:
=> [Fix] Fix the output of scatter on MLU device

setup.py
The *.mlu files are MLU operator source code, and should be compiled by MLU compiler.
Add file path to setup.py.
No BC-breaking.
Support unittest of MLU.
Support network training by MLU.
**Before PR**:
**After PR**:
=> [Fix] Add MLU kernels to be compiled

mmcv/parallel/distributed.py
Currently all tagged versions of torch 1.11.0 have version 1.11.0a0. Previously the comparison to 1.11.0 failed and self._sync_params() was still used, causing an error. This fix should include all versions of 1.11.
Changed a line of code to include prerelease versions in version checking.
N/A
N/A
**Before PR**:
**After PR**:
=> [Fix] Fixed version comparison to include prerelease versions

mmcv/utils/config.py, tests/test_utils/test_config.py
Resolves #1112
Adds `--cfg-options key=none` functionality.
None that I'm aware of.
**Before PR**:
**After PR**:
=> [Enhancement] Support None in DictAction

mmcv/utils/env.py
On my Windows, the console output is using utf-8. But the `defaultlocale` gives gbk, which cause decoding error. 
I found `os.device_encoding(1)` gives correct encoding. 
Change the way to get encoding of console output. 
None
None
**Before PR**:
**After PR**:
=> [Fix] Get correct encoding in Windows for collect_env()

mmcv/utils/config.py, tests/test_utils/test_config.py
Ensure the type of filename parameter in Config is str.
As above.
**Before PR**:
**After PR**:
=> [Fix] Ensure the type of filename parameter in Config is str

mmcv/ops/csrc/common/cuda/nms_rotated_cuda.cuh
Shared memory size is `threadsPerBlock * 5`, write `block_boxes[threadIdx.x * 6 + 5]` is illegal.
Fix block_boxes index.
=> [Fix] Fix nms rotate illegal memory access

.github/workflows/build.yml
Refer to https://github.com/open-mmlab/mmocr/pull/988
Nvidia has rotated its public key the old keys in cuda docker images all become invalid. This PR implements a hotfix on affected configurations which explicitly fetches and applies the latest GPG keys before apt-get update. See https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901
This PR also updates the test-skipping rule in CirleCI and Github Action. Modifying the CI configuration of one CI provider will not trigger the full tests on …
=> [Fix] Fix GPG key error in CI

.dev_scripts/visualize_lr.py, setup.cfg
Add learning rate visualization script. The learning rate curve of target schedule registered in `EpochBasedRunner or IterBasedRunner` can be plot  as follows:
`python ./visualize_lr.py schedule_config.py `
The schedule_config.py can be:
```
lr_config = dict(
policy='cyclic',
target_ratio=(10, 1e-4),
cyclic_times=5,
step_ratio_up=0.4,
)
momentum_config = dict(
policy='cyclic',
target_ratio=(10, 1e-4),
cyclic_times=5
)
runner = …
```
=> [Feature] Add a script to visualize lr

mmcv/image/geometric.py
Resolves #1894 
Since Pillow v9.1.0, it uses a slightly different naming scheme for filters, and the original scheme will be deprecated and removed in Pillow v10 (2023-07-01). More details can be found at https://github.com/python-pillow/Pillow/pull/5954 and https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#deprecations.
This PR fixes the issue by checking the Resampling filter naming before setting `pillow_interp_codes`.
- Update mmcv/image/geometric.py
No
=> [Enhancement] Add support for latest Pillow resampling filter naming scheme

docs/en/conf.py, docs/zh_cn/conf.py
Add `myst_heading_anchors=4` in `docs/en/conf.py` to fix the error that the heading anchors do not work.
- Before the PR
- After the PR
If this PR introduces a new feature, it is better to list some use cases here, …
=> [Docs] Fix heading anchor in documentation

mmcv/ops/csrc/common/cuda/bbox_overlaps_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.cu
Building failed on some cuda arch.  https://github.com/NVIDIA/nccl/issues/9
Add CUDA ARCH check.
**Before PR**:
**After PR**:
=> [Fix] Fix bbox overlap fp16

mmcv/ops/merge_cells.py, tests/test_ops/test_merge_cells.py
Fix the bug met in using nasfpn which is mentioned at https://github.com/open-mmlab/mmdetection/issues/3401.
Avoid the strong restrictions of _resize function in BaseMergeCell:
1. When Downsampling the feature map, the feature map's shape must be divisible by the target size. We pad zero around feature map before max_pool2d opt to make it always divisible. (line 102 ~ 107)
2. Considering the different downsampling scale of H and W, shape[-2] and shape[-1] are involed in the definition of kernel_size. (line 110)
Does the …
=> [Enhancement] Lower the restrictions of _resize method in BaseMergeCell

tests/test_ops/test_rotated_feature_align.py
Signed-off-by: del-zhenwu <dele.zhenwu@gmail.com>
Skip CPU test in `test_rotated_feature_align.py` for parrots
Update tests/test_ops/test_rotated_feature_align.py
No
**Before PR**:
**After PR**:
=> [Fix] Skip CPU test in test_rotated_feature_align.py for parrots

mmcv/parallel/utils.py, tests/test_parallel.py
In order to avoid scope collision with other codebases, DistributedDataParallelWrapper in mmrazor, mmpose, mmedit or some other codebases need to be registered to a separate registry whose parent is the MODULE_WRAPPERS registry in mmcv. Ref to [this pr](https://github.com/open-mmlab/mmpose/pull/1204). When checking if a module is a module wrapper, we need to consider these child MODULE_WRAPPERS.
A Depth-First-Search is needed in ``is_module_wrapper``.
=> [Fix]Fix is_module_wrapper

mmcv/runner/hooks/evaluation.py
When reading the docstrings in `EvalHook`,I found it's contradictory to code.
See files.
**Before PR**:
**After PR**:
=> [fix]:fix docstrings in EvalHook

mmcv/runner/epoch_based_runner.py, mmcv/runner/iter_based_runner.py
The wrong labeling of the dataset may cause problems such as gradient explosion during the training process. The wrong labeling can be found by setting up a hook function.
However, when a for loop is used to traverse the iterator of the pytorch `DataLoader` class, the `hook` cannot obtain the information of the currently read image, and thus cannot determine the source of the error.
Load the data_batch information into the `runner` during the train process, and then pass it to the hook function to solve the problem.
It's just a very small imporvement.
=> Imporve ability to view usage data during training

requirements/test.txt
Fix `TypeError: Descriptors can not be created directly` caused by the new version of protobuf.
https://github.com/open-mmlab/mmcv/runs/6603582273?check_suite_focus=true#step:13:95
References:
- https://discuss.streamlit.io/t/typeerror-descriptors-cannot-not-be-created-directly/25639/5
- https://discuss.streamlit.io/t/streamlit-run-with-protocbuf-error/25632/4
- Update requirements/test.txt
If so, please describe how it …
=> [Fix] Fix protobuf compatible error

mmcv/runner/builder.py
Add type hints for runner/builder
- Update mmcv/runner/builder.py
No
**Before PR**:
**After PR**:
=> Add type hints for runner/builder

mmcv/ops/active_rotated_filter.py
Add type hints in mmcv/ops/active_rotated_filter.py
Add type hints
**Before PR**:
**After PR**:
=> Add type hints in mmcv/ops/active_rotated_filter.py

mmcv/ops/point_sample.py
Add type hints in mmcv/ops/point_sample.py
Add type hints in mmcv/ops/point_sample.py
**Before PR**:
**After PR**:
=> Add type hints in mmcv/ops/point_sample.py

mmcv/ops/focal_loss.py
To get gift.
Add type hint in focal_loss.py.
**Before PR**:
**After PR**:
=> [Enhance] Add type hint in `focal_loss.py`.

mmcv/runner/base_module.py, mmcv/runner/checkpoint.py, mmcv/runner/default_constructor.py, mmcv/runner/dist_utils.py, mmcv/runner/fp16_utils.py, mmcv/runner/log_buffer.py, mmcv/runner/priority.py
Add type hints in these files:
'base_module.py', 'checkpoint.py',
'default_constructor.py',
'dist_utils.py', 'fp16_utils.py',
'log_buffer.py', 'priority.py'.
**Before PR**:
**After PR**:
=> [Enhance] Add type ints in these files:

mmcv/ops/ball_query.py, mmcv/ops/border_align.py, mmcv/ops/correlation.py, mmcv/ops/deform_conv.py, mmcv/ops/deform_roi_pool.py
Add type hints for files in mmcv/ops.
Add type hints for files in mmcv/ops:
- ball_query.py
- border_align.py
- correlation.py
- deform_conv.py,
- deform_roi_pool.py
- deprecated_wrappers.py [**NO type hints need to be added in this file**]
**Before PR**:
**After PR**:
=> Add type hints for mmcv/ops

docs/en/conf.py, docs/zh_cn/conf.py
change the year from 2018-2021 to 2018-2022
=> [Docs] Update copyright years in docs

mmcv/ops/csrc/common/mlu/common_mlu_helper.hpp, mmcv/ops/csrc/common/mlu/roi_align_rotated_mlu_kernel.mlu, mmcv/ops/csrc/common/mlu/roi_align_rotated_utils.hpp, mmcv/ops/csrc/pytorch/mlu/roi_align_rotated_mlu.cpp, tests/test_ops/test_roi_align_rotated.py
The motivation of the PR is to support running RoiAlignRotated with Cambricon MLU backend.
Add roi_align_rotated_mlu_kernel.mlu src code as mlu kernel.
Add roi_align_rotated_mlu.cpp to support launching kernel in pytorch.
Refactor test_roi_align_rotated.py to support testing RoiAlignRotated with MLU backend.
MLU src code
Add MLU src code of RoiAlignRotated in directory mmcv/ops/csrc/common/mlu/roi_align_rotated_mlu_kernel.mlu.
Pytorch adaptation
Adapt RoiAlignRotated for pytorch in …
=> [Feature] Support RoiAlignRotated with cambricon MLU backend

mmcv/ops/__init__.py, mmcv/ops/csrc/common/cuda/iou3d_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/cuda/iou3d_cuda.cu, mmcv/ops/csrc/pytorch/iou3d.cpp, mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/iou3d.py, tests/test_ops/test_iou3d.py
Fix a bug introduced in #1902. Actually `boxes_iou3d` was calculating `bev iou`. Now it is fixed. Also `boxes_overlap_bev` is now a public function and can be used not only to calculate `3d iou` but also `3d iof` in `mmdetection3d`.
Fix `boxes_iou3d` in python and cuda. Add `boxes_overlap_bev` and corresponding tests.
No. Actually `boxes_iou3d` was not used in `mmdetection3d` and now it is just fixes.
May by @ZwwWayne or @Tai-Wang can have a look about `mmdetection3d` connection.
=> [Fix] make iou3d.boxes_iou3d actually calculate 3D IoU

mmcv/ops/nms.py, tests/test_ops/test_nms_rotated.py
When set `class_agnostic=False` in `batched_nms`, it will add an offset to det boxes, for horizional bbox in xyxy, the code works fine. But in rotated box (x_ctr, y_ctr, w, h, angle), only center point need offset, so I add a branch to solve that.
Add type hint for nms.py. #1948 
- Update mmcv/ops/nms.py
- Update tests/test_ops/test_nms_rotated.py
If so, please describe how it breaks the compatibility and how the …
=> Fix batched_nms for rotated box and add type hint for nms.py

mmcv/ops/csrc/parrots/cudabind.cpp, mmcv/ops/csrc/parrots/iou3d.cpp, mmcv/ops/csrc/parrots/iou3d_parrots.cpp, mmcv/ops/csrc/parrots/iou3d_pytorch.h
=> [Fix] Fix iou3d in parrots

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md
Reformat op docs.Add devices information.
Reformat `ops.md`
**Before PR**:
**After PR**:
=> [Docs] Reformat op docs

.github/workflows/build.yml, mmcv/utils/__init__.py, mmcv/utils/torch_ops.py, tests/test_utils/test_torch_ops.py
PyTorch is in the process of changing the behaviour of `torch.meshgrid`, and this results in a warning when using this method without an `indexing` argument as of PyTorch 1.10. The problem is that prior to PyTorch 1.10 these is no such argument, and thus for compatibility reasons it can't just be added. PyTorch 1.8.2 is an LTS release, so this issue will likely not go away any time soon, and eventually PyTorch will make a breaking change that changes the default behaviour of the method when called without an indexing argument:
https://pytorch.org/docs/stable/generated/torch.meshgrid.html
https://github.com/pytorch/pytorch/issues/50276
While mmcv has no calls to `torch.meshgrid`, many other repos do (this is not an exhaustive list):
https://github.com/open-mmlab/mmclassification/pull/860 …
=> Add torch_meshgrid_ij wrapper due to PyTorch change

mmcv/runner/base_runner.py, mmcv/runner/checkpoint.py, mmcv/runner/epoch_based_runner.py, mmcv/runner/hooks/lr_updater.py, mmcv/runner/iter_based_runner.py
Add type hints for runner/base_runner.
- mmcv/runner/base_runner.py
- mmcv/runner/checkpoint.py
- mmcv/runner/epoch_based_runner.py
- mmcv/runner/hooks/lr_updater.py
- mmcv/runner/iter_based_runner.py
No
**Before PR**:
**After PR**:
=> Add type hints for runner/base_runner

mmcv/ops/fused_bias_leakyrelu.py, mmcv/ops/gather_points.py, mmcv/ops/group_points.py, mmcv/ops/knn.py, mmcv/ops/masked_conv.py, mmcv/ops/merge_cells.py, mmcv/ops/min_area_polygons.py, mmcv/ops/modulated_deform_conv.py, mmcv/ops/multi_scale_deform_attn.py
[Enhance] Add type hints in /ops:
`fused_bias_leakyrelu.py`, 'gather_points.py`, `group_points.py`.
There is no need to add type hints in `furthest_point_sample.py` and
`info.py`.
As for `focal_loss.py`, please see #1994.
**Before PR**:
**After PR**:
=> [Enhance] Add type hints in /ops:

mmcv/ops/csrc/tensorrt/plugins/trt_deform_conv.cpp, mmcv/ops/csrc/tensorrt/plugins/trt_modulated_deform_conv.cpp
DCN and mDCN TensorRT plugins can not read the deform_groups.
Update the attribute name.
**Before PR**:
**After PR**:
=> [Fix] Fix mdcn trt

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/common/mlu/common_mlu_helper.hpp, mmcv/ops/csrc/common/mlu/roi_pool_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/roi_pool_mlu.cpp, tests/test_ops/test_roi_pool.py
The motivation of the PR is to support running RoiPool with Cambricon MLU backend.
1. Add `roi_pool_mlu_kernel.mlu` src code as MLU kernel.
2. Add `roi_pool_mlu.cpp` to support launching kernel in PyTorch.
3. Refactor `test_roi_pool.py` to support testing RoiPool with MLU backend.
* MLU src code
Add MLU src code of RoiPool in directory `mmcv/ops/csrc/common/mlu/roi_pool_mlu_kernel.mlu`.
* PyTorch adaptation
Adapt RoiPool for PyTorch in `mmcv/ops/csrc/pytorch/mlu/roi_pool_mlu.cpp`.
* Common functions
Add …
=> [Feature] Support RoiPool with Cambricon MLU backend

mmcv/ops/points_sampler.py
fix index error when using multi-samplers strategy
Just change index from last_fps_end_index:fps_sample_range to last_fps_end_index:fps_sample_range +last_fps_end_index based on the issue https://github.com/open-mmlab/mmcv/issues/2082
If this PR introduces a new feature, it …
=> [Fix] Fix index error when using multi-samplers strategy

mmcv/parallel/distributed.py
Related issue: https://github.com/open-mmlab/mmsegmentation/issues/1742
Make `MMDistributedDataParallel` compatible with Pytorch 1.12.
Since https://github.com/pytorch/pytorch/blob/67ece03c8cd632cce9523cd96efde6f2d1cc8121/torch/nn/parallel/distributed.py#L969
does not use  `MMDistributedDataParallel.to_kwargs` to process data. `MMDistributedDataParallel` should patch `torch.distributed.utils._to_kwargs` with `MMDistributedDataParallel.to_kwargs` during the forward process.
Please briefly describe what modification is made in …
=> [Fix] Make `MMDistributedDataParallel` compatible with Pytorch1.12

mmcv/runner/hooks/profiler.py
Implements #2118
https://pytorch.org/docs/master/profiler.html?highlight=tensorboard_trace_handler#torch.profiler.tensorboard_trace_handler
- Make `dir_name` optional for ProfilerHook configurations usin TensorBoard profiling output
- Make `dir_name` relative to `runner.work_dir` rather than the current working directory.
**Before PR**:
- N/A
- N/A
**After PR**:
=> [Enhancement] Improve ProfilerHook beaviour when using a relative (or empty) dir_name

mmcv/image/photometric.py, tests/test_image/test_photometric.py
the training acc drops in mmselfsup if using cv2 backend
**Before PR**:
**After PR**:
=> [Refactor] add pillow backend for ColorJitter related functions

mmcv/runner/hooks/logger/pavi.py, tests/test_runner/test_hooks.py
Support setting start epoch and interval epoch for PAVI Logger Hook
Add new param for PAVI logger Hook for setting start epoch and interval epoch.
Nothing
```py
hook = PaviLoggerHook(
add_graph_kwargs={
'active': False,
'start': 0,
'interval': 1
},
add_last_ckpt=True,
add_ckpt_kwargs={
'active': True,
'start': 1,
'interval': 2
})
runner.register_hook(hook)
```
**Before PR**:
**After PR**:
=> [Feature] Support setting start epoch and interval epoch for PAVI Logger Hook

tests/test_ops/test_onnx.py
Since ONNXRuntime 1.9, the providers parameter of InferenceSession are required explicitly. So add this parameter when initializing the InferenceSession object.
tests/test_ops/test_onnx.py
No
**Before PR**:
**After PR**:
=> [Fix] Fix test_onnx tests

mmcv/ops/multi_scale_deform_attn.py
[Please describe the motivation of this PR and the goal you want to achieve through this PR.](https://github.com/open-mmlab/mmcv/blob/fb7959624ecde7a21d0c455c548573db7252aab4/mmcv/ops/multi_scale_deform_attn.py#L238 
thetas is created on cpu.
An error occurs if model.init_weights() is executed after model.to(device).) …
=> [Fix] Fix init weights

mmcv/runner/hooks/optimizer.py, tests/test_runner/test_hooks.py
Fix https://github.com/open-mmlab/mmcv/issues/2083
- Fix the issue
- Eliminate the calculation of `residual_iters` to avoid complicated implementation of `mmcv/runner/hooks/optimizer.py` and unit tests (I think the logic has another bug because [`every_n_iters`](https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/hooks/hook.py#L61-L62) has not been modified for it.)
- Put the same code into `_get_loss_factor`
Since the bug causes wrong loss, models trained by simultaneous use of GradientCumulativeOptimizerHook and resume will show different results before and after this PR.
**Before PR**:
**After PR**:
=> [Fix] Fix gradient cumulative optimizer when resuming

mmcv/runner/hooks/logger/mlflow.py
Recreated #2188 since I did not use a feature branch.
I want to log (hyper)parametrers in MLFLow to be able to compare them between runs.
Adds the argument "params" to MlflowLoggerHook. This works in the same way as the existing argument "tags" in that it runs mlflow.log_params() in before_run().
No.
See motivation.
**Before PR**:
**After PR**:
=> [Feature] Add argument params to MlflowLoggerHook

mmcv/ops/csrc/common/cuda/prroi_pool_cuda_kernel.cuh
Fix a potential bug in PrRoIPool op
Due to the limitation of memory in https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/common/cuda/common_cuda_helper.hpp#L24,  we should prevent memory overflow of pointers in PrRoIPool op when there are many roi bboxes.
Fix a potential bug about memory overflow in PrRoIPool op
**Before PR**:
**After PR**:
=> [Fix] Fix a potential bug in PrRoIPool op

mmcv/fileio/file_client.py
1. Avoid replacing `path` with the responding key in `path_mapping` many times.
related https://github.com/open-mmlab/mmcv/pull/2197
1. Add `1` in `filepath = filepath.replace(k, v)` …
=> [Fix] Path mapping only once in storage backends

mmcv/ops/modulated_deform_conv.py
Fix the bug in ModulatedDeformConv2dFunction to enable training with AMP.
The snippet of the error message is as below:
```
"/mnt/cache/xxx/mmediting/mmedit/models/editors/basicvsr_plusplus_net/basicvsr_plusplus_net.py", line 413, in forward
return modulated_deform_conv2d(x, offset, mask, self.weight, self.bias,
File "/mnt/cache/zengyanhong/mmcv/mmcv/ops/modulated_deform_conv.py", line 76, in forward
ext_module.modulated_deform_conv_forward(
RuntimeError: expected scalar type Float but found Half
```
torch:  1.8.0+cu111
cast the …
=> [Fix] cast the type of mask to enable training with amp

.dev_scripts/check_installation.py, .github/workflows/build.yml, .github/workflows/publish-to-pypi.yml, README.md, README_zh-CN.md, docker/README.md, docker/dev/Dockerfile, docker/release/Dockerfile, docs/en/get_started/installation.md, docs/zh_cn/get_started/installation.md, mmcv/cnn/bricks/transformer.py, setup.py
Since **mmcv v2.0.0rc1**, we rename the package name `mmcv to mmcv-lite` and `mmcv-full to mmcv` for two reasons:
- Most users use mmcv-full, but it is inconsistent with the name of the repo, which will lead to confusion
- Users include mmcv-full in the requirements, but the mmcv repo cannot show the downstream libraries that use mmcv
**Before this PR**
- install mmcv with ops
```bash
pip install mmcv-full -f xxxx
pip install mmcv-full
```
- install mmcv without ops …
=> Rename mmcv package name

docs/zh_cn/understand_mmcv/registry.md
def converter2(a, b):
return Converter1(a, b)
=> [Docs] Fix the example error in registry.md

mmcv/runner/checkpoint.py
Hi OpenMMLab team,
First of all thank you very much for developing your awesome framework.
TorchVision has recently introduced a new [Model Registration API](https://pytorch.org/blog/easily-list-and-initialize-models-with-new-apis-in-torchvision/) which allows the easier listing of models and weights. Its aim is to eliminate the somehow hacky idiom of using `torchvision.models.__dict__` to retrieve models and weights.
In this PR, I'm updating your existing implementation introduced at https://github.com/open-mmlab/mmcv/issues/1848 to use our new API. Please note that I'm going for the minimum number of modifications necessary; the code may be further simplified but that might require additional discussion.
For full transparency, the new API is currently considered Beta. We've …
=> Add support of TorchVision's Model Registration API on MMCV

mmcv/device/__init__.py, mmcv/device/npu/__init__.py, mmcv/device/npu/_functions.py, mmcv/device/npu/data_parallel.py, mmcv/device/npu/distributed.py, mmcv/device/npu/scatter_gather.py, mmcv/device/utils.py, mmcv/runner/dist_utils.py, mmcv/runner/hooks/optimizer.py, mmcv/utils/__init__.py, mmcv/utils/device_type.py, tests/test_device/test_device_utils.py, tests/test_device/test_functions.py, tests/test_device/test_npu/test_npu_parallel.py
Added ascending device support in mmcv.
- The main modification points are as follows: 
1. In ```mmcv/device/```, We've added our NPU devices. Since the NPU does not support the DataParallel mode, DP and DDP have been customized, the Scatter related methods have been rewritten, and the use case of MLU has been referenced, thanks.
2. In ```mmcv/runner/dist_utils.py```, We have added NPU-related distributed initialization methods.
3. In ```mmcv/runner/hooks/optimizer.py```, We've added the amp method on npu.
4. In …
=> [Feature] Support engine with NPU backend.

mmcv/ops/masked_conv.py
Fix the calculation error of out_w in MaskedConv2dFunction and this function can not work in torch1.6 due to / operator. More details at https://app.circleci.com/pipelines/github/open-mmlab/mmcv/1574/workflows/3056e22f-a35d-4a55-995f-e66f3acdcc23/jobs/3077?invite=true#step-107-177.
mmcv/ops/masked_conv.py
No
**Before PR**:
**After PR**:
=> [Fix] Fix the calculation error of out_w in MaskedConv2dFunction

docs/en/understand_mmcv/data_process.md, docs/zh_cn/understand_mmcv/data_process.md
=> [Docs] Fix some mistakes in data_process.md

README.md, README_zh-CN.md, docs/en/get_started/build.md, docs/en/get_started/installation.md, docs/zh_cn/get_started/build.md, docs/zh_cn/get_started/installation.md
=> [Docs] Add reminder in docs for macOS M1 users

.github/workflows/build.yml, mmcv/ops/csrc/common/cuda/nms_cuda_kernel.cuh, mmcv/ops/csrc/parrots/cudabind.cpp, mmcv/ops/csrc/parrots/iou3d.cpp, mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/cuda/iou3d_cuda.cu, mmcv/ops/csrc/pytorch/iou3d.cpp, mmcv/ops/iou3d.py, tests/test_ops/test_iou3d.py
This PR update the nms op in iou3d.
It is used to support MLU ops in the future.
Move gather index into kernel.
**Before PR**:
**After PR**:
=> [Refactor] Refactor the nms3d op to support MLU

.pre-commit-config-zh-cn.yaml, .pre-commit-config.yaml, docs/en/understand_mmcv/data_process.md, docs/zh_cn/understand_mmcv/data_process.md, mmcv/ops/active_rotated_filter.py, mmcv/ops/csrc/pytorch/mlu/psamask_mlu.cpp, mmcv/ops/csrc/pytorch/mlu/roi_align_mlu.cpp, mmcv/ops/rotated_feature_align.py, mmcv/video/io.py, setup.cfg
Related PR: #2317
The motivation to upgrade some versions of pre-commit hooks to latest is that `importlib-metadata v5.0.0` which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581. …
=> Upgrade the versions of pre-commit hooks

mmcv/runner/hooks/logger/dvclive.py, tests/test_runner/test_hooks.py
Updating the [DVCLive hook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/dvclive.py) according [the latest changes](https://github.com/iterative/dvclive/pull/318) in the way we use loggers in DVCLive.
- Added a way to pass a `dvclive` instance into the hook
**Before PR**:
**After PR**:
=> [Enhancement] Add ability to pass logger instance to frameworks

.pre-commit-config.yaml, README.md, mmcv/ops/csrc/pytorch/npu/focal_loss_npu.cpp
=> Npu-dev: FocalLoss Adapter BugFix

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/__init__.py, mmcv/ops/box_iou_quadri.py, mmcv/ops/csrc/common/box_iou_rotated_utils.hpp, mmcv/ops/csrc/common/cuda/box_iou_quadri_cuda.cuh, mmcv/ops/csrc/common/cuda/nms_quadri_cuda.cuh, mmcv/ops/csrc/pytorch/box_iou_quadri.cpp, mmcv/ops/csrc/pytorch/cpu/box_iou_quadri.cpp, mmcv/ops/csrc/pytorch/cpu/nms_quadri.cpp, mmcv/ops/csrc/pytorch/cuda/box_iou_quadri_cuda.cu, mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/cuda/nms_quadri_cuda.cu, mmcv/ops/csrc/pytorch/nms_quadri.cpp, mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/nms.py, tests/test_ops/test_box_iou_quadri.py, tests/test_ops/test_nms_quadri.py
Add `box_iou_quadri` and `nms_quadri` ops, which used by quadrilateral boxes detection in https://github.com/open-mmlab/mmrotate/pull/520
**Before PR**:
**After PR**:
=> [Feature] Add box_iou_quadri & nms_quadri

mmcv/ops/csrc/common/pytorch_mlu_helper.hpp, mmcv/ops/csrc/pytorch/mlu/nms_mlu.cpp
The motivation of the PR is to add getJobLimitCapability interface, and replace cluster_number * core_dim by it in nms.
1. Refactor mmcv/ops/csrc/common/pytorch_mlu_helper.hpp to add getJobLimitCapability interface.
2. Refactor mmcv/ops/csrc/pytorch/mlu/nms_mlu.cpp to replace cluster_number * core_dim by getJobLimitCapability interface.
If so, please describe how it breaks the compatibility and how the downstream …
=> [Enhancement] Add getJobLimitCapability interface and use it in nms

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/common/mlu/iou3d_mlu_kernel.mlu, mmcv/ops/csrc/common/mlu/iou3d_utils.hpp, mmcv/ops/csrc/pytorch/mlu/iou3d_mlu.cpp, tests/test_ops/test_iou3d.py
The motivation of the PR is to support running Iou3d with Cambricon MLU backend.
1. Add iou3d_mlu_kernel.mlu src code as MLU kernel.
2. Add iou3d_mlu.cpp to support launching kernel in PyTorch.
3. Refactor test_iou3d.py to support testing DeformRoiPool with MLU backend.
- MLU src code
Add MLU src code of Iou3d in directory mmcv/ops/csrc/common/mlu/iou3d_mlu_kernel.mlu.
- PyTorch adaptation
Adapt Iou3d for PyTorch in mmcv/ops/csrc/pytorch/mlu/iou3d_mlu.cpp.
- Unit test
Support test Iou3d with various …
=> [Feature]Support Iou3d with cambricon MLU backend

mmcv/ops/csrc/common/cuda/correlation_cuda.cuh, mmcv/ops/csrc/pytorch/cuda/correlation_cuda.cu
https://github.com/open-mmlab/mmcv/issues/2263
thread idx is computed with:
```c++
const int h = blockIdx.y * blockDim.y + threadIdx.y;
const int w = blockIdx.z * blockDim.z + threadIdx.z;
```
Where `threadIdx.y` and `threadIdx.x` are always 4. Which might lead to some errors.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this …
=> [Fix] Fix Correlation op

mmcv/runner/hooks/logger/wandb.py, tests/test_runner/test_hooks.py
Log best metric/loss with wandb.
```
log_config = dict(
interval=50,
ignore_last=False,
hooks=[
dict(type='TextLoggerHook'),
dict(type='WandbLoggerHook',
define_metric_cfg=dict(bbox_mAP='max'),
init_kwargs=dict(
project='example',
name='example001'
))
])
```
Example result
**Before PR**:
**After PR**:
=> [Enhancement] wandb define_metric

mmcv/ops/points_sampler.py
The result of `calc_square_dist()` function could be`NaN` according to the issue https://github.com/open-mmlab/mmcv/issues/2178.
We directly use `torch.cdist` to calculate the square distance instead. …
=> [Fix] Fix the potential `NaN` bug in `calc_square_dist()`

README.md, README_zh-CN.md, docs/en/get_started/installation.md, docs/zh_cn/get_started/installation.md
=> [Docs] Update README and fix typo in docs

README.md, README_zh-CN.md, docs/en/get_started/build.md, docs/zh_cn/get_started/build.md
change the notice on README and build.md for macos users
modified:   README.md
modified:   README_zh-CN.md
modified:   docs/en/get_started/build.md
modified:   docs/zh_cn/get_started/build.md
**Before PR**:
**After PR**:
=> [2.x Docs] Macos build notice

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/common/mlu/roiaware_pool3d_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/roiaware_pool3d_mlu.cpp, tests/test_ops/test_roiaware_pool3d.py
The motivation of the PR is to support running RoiawarePool3d with Cambricon MLU backend.
1. Add roiaware_pool3d_mlu_kernel.mlu src code as MLU kernel.
2. Add roiaware_pool3d_mlu.cpp to support launching kernel in PyTorch.
3. Refactor test_roiaware_pool3d.py to support testing RoiawarePool3d with MLU backend.
- MLU src code
Add MLU src code of RoiawarePool3d in directory mmcv/ops/csrc/common/mlu/roiaware_pool3d_mlu_kernel.mlu.
- PyTorch adaptation
Adapt RoiawarePool3d for PyTorch in mmcv/ops/csrc/pytorch/mlu/roiaware_pool3d_mlu.cpp.
- Unit test
Support test RoiawarePool3d with various backends in tests/test_ops/test_roiaware_pool3d.py.
If so, please …
=> [Feature] Support RoiawarePool3d with cambricon MLU backend.

mmcv/ops/masked_conv.py
=> Masked_conv2d NPU

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md
Nowadays we have been developing mmcv.ops on ascend-npu device, and some developments have been finished. This PR is used for updating the ops  in the docs(ops.md) , which is already for npu-device.
=> [Fea]: add currently-npu-supported-ops in ops.md docs

mmcv/ops/roi_align.py
Torch>=1.13 would not wrap Graph into GraphContext, so we can not reuse some tools in `torch.onnx`.
Update roi_align symbolic.
**Before PR**:
**After PR**:
=> fix roi align symbolic for torch>1.13

mmcv/transforms/processing.py
Fix the problem of assertion and arguments don't match 
- mmcv/transforms/processing.py
=> [Fix] fix assertion at RandomChoiceResize

mmcv/fileio/file_client.py, tests/test_fileclient.py
Add conf_path in PetrelBackend initial parameters to set user-defined petrel client config path.
Add conf_path in PetrelBackend initial parameters to set user-defined petrel client config path.
If this PR introduces a new feature, it is better to list some use cases here, and …
=> feat: add conf_path in PetrelBackend

docs/en/get_started/build.md, docs/en/understand_mmcv/ops.md, docs/zh_cn/get_started/build.md, docs/zh_cn/understand_mmcv/ops.md
update docs
Modify some NPU-related documentation and installation instructions.
=> [Docs] Replace NPU with Ascend in installation documentation

mmcv/ops/multi_scale_deform_attn.py, tests/test_ops/test_ms_deformable_attn.py
Modified for use with ViT-Adapter.
https://github.com/czczup/ViT-Adapter/blob/main/detection/ops/modules/ms_deform_attn.py#L29
https://github.com/open-mmlab/mmclassification/pull/1209
https://github.com/open-mmlab/mmdetection/pull/9354
**Before PR**:
**After PR**:
=> [Enhancement] Support value_proj_ratio in MultiScaleDeformableAttention

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/deform_roi_pool.cpp, tests/test_ops/test_deform_roi_pool.py
This PR contains a npu-adapter of mmcv ops-deformableroipool. we can run these ops(above) on ascend-npu device by these adapters.
deform_roi_pool.cpp is added to the PR which is used for deformroipool npu-adaptation, while  test_deform_roi_pool.py is modified by the PR.
=> add npu adapter for deformableroipool

mmcv/cnn/rfsearch/search.py, tests/test_cnn/test_rfsearch/test_search.py
RF-Next(TPAMI2022) has been merged in [PR](https://github.com/open-mmlab/mmcv/pull/2056).
But when I apply RF-Next to `mmsegmentation`, I found that some codes should be revised. 
Current code will skip a layer when the `config.search.skip_layer` includes one of the subnames of this layer, 
rather than the full name. 
For example,  if I want to skip a layer named `layer.0.conv` during searching, I should add `layer` / `0` / `conv`  to `config.search.skip_layer`. However, this will cause other layers to be incorrectly skipped, e.g., `layer.1.conv`.
So the codes should be revised to to judge whether a layer should be skipped according to its full name.
Determine whether a layer should be skipped according to the full_name.
`
if any(layer in fullname for layer in …
=> Fix skip_layer for RF-Next

mmcv/runner/hooks/evaluation.py
Fix a typo in runner/hooks/evaluation.py
=> [Fix] Fix a typo in runner/hooks/evaluation.py

mmcv/ops/csrc/common/mlu/ms_deform_attn_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/ms_deform_attn_mlu.cpp
The motivation of the PR is to improve the performance of ms_deform_attn on Cambricon MLU backend, especially for small channel cases.
MLU src code
Modify MLU src code of ms_deform_attn_mlu_kernel in directory mmcv/ops/csrc/common/mlu/ms_deform_attn_mlu_kernel.mlu.
PyTorch adaptation
Modify ms_deform_attn for PyTorch in mmcv/ops/csrc/pytorch/mlu/ms_deform_attn_mlu.cpp. …
=> [Enhance] Optimize the performace of ms_deform_attn for MLU device

mmcv/transforms/processing.py
resolves #2526
`_flip_keypoint` of `RandomFlip` returns the wrong result. `_flip_keypoint` should concatenate the flipped rather than input `keypoints`.
`_flip_keypoint` of `RandomFlip`
No
**Before PR**:
**After PR**:
=> [Fix] Fix _flip_keypoint of RandomFlip returns the wrong result

mmcv/ops/csrc/common/utils/spconv/paramsgrid.h, mmcv/ops/csrc/pytorch/npu/psa_mask_npu.cpp
Fix c++/cuda lint failed.
**Before PR**:
**After PR**:
=> [Fix] Fix c++/cuda lint failed

.circleci/test.yml, requirements/test.txt
Since onnx 1.13 deprecated the [protobuf<=3.20.2](https://github.com/onnx/onnx/blob/v1.13.0/requirements-release.txt#L4), and the version of protobuf also could not be too high for #1992. This PR keeps the version of protobuf 3.20.x
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
=> [Fix] Fix CI failed caused by protobuf

.github/workflows/build.yml
The CI job failed: https://github.com/open-mmlab/mmcv/actions/runs/3826436209/jobs/6566398257
The mmcv-full compile failed because the Python C-API header include directory is wrong:
In the CI container:
This is a bug introduce by setuptools [v65.2.0](https://github.com/pypa/setuptools/pull/3258), and the verison of setuptools for python 3.10.9 in setup-python action is 65.5.0 (while 63.2.0 for python3.10.8).
Related links:
- https://github.com/pypa/setuptools/issues/3589
- https://github.com/pypa/distutils/issues/178
A workaround is use `setuptools<=65.1.0` when python==3.10
=> [Fix] Fix CI failed caused by 'Python.h' not found

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/__init__.py, mmcv/ops/bezier_align.py, mmcv/ops/csrc/common/cuda/bezier_align_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/bezier_align.cpp, mmcv/ops/csrc/pytorch/cpu/bezier_align.cpp, mmcv/ops/csrc/pytorch/cuda/bezier_align_cuda.cu, mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/pybind.cpp, tests/test_ops/test_bezier_align.py
=> [Feature] Add BezierAlign CUDA op

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/roi_pool_npu.cpp, tests/test_ops/test_roi_pool.py
add roi_pool npu op
add roi_pool npu op
=> [Feature] Add Ascend support for RoIPool op

mmcv/ops/modulated_deform_conv.py, tests/test_ops/test_modulated_deform_conv.py
Let DCN of MLU support amp mode.
mmcv/ops/modulated_deform_conv.py ：  cast input with offset
tests/test_ops/test_modulated_deform_conv.py  ：  add amp test for MLU 
**Before PR**:
**After PR**:
=> [Enhance] Add AMP support for MLU_DCNv2

mmcv/image/io.py, mmcv/transforms/loading.py, tests/test_image/test_io.py, tests/test_transforms/test_transforms_loading.py
PR (#2468) directly removed the `file_client_args` parameter and it causes bc issue. This PR fixes this issue. …
=> fileio related interfaces should keep bc

mmcv/ops/deform_conv.py, mmcv/ops/modulated_deform_conv.py
When performing the MLU-based PyTorch1.6 test, because PyTorch1.6-mlu does not support DCN,
the local test case will report an error.
mmcv/ops/deform_conv.py： 
-Put the assert of torchvision version in the function
-Simplified weight syntax
mmcv/ops/modulated_deform_conv.py：
-Put the assert of torchvision version in the function
**Before PR**:
**After PR**:
=> [Fix] Check the version of torchvision in __init__ of DCN

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/nms_rotated.cpp, mmcv/ops/csrc/pytorch/npu/nms_rotated_npu.cpp, mmcv/ops/csrc/pytorch/pybind.cpp, mmcv/ops/nms.py, tests/test_ops/test_nms_rotated.py
This PR is for adaptation of the op which name is "nms_rotated" on ascend npu device. You can use the op on npu-device by this PR.  
The PR has been tested on npu-device, the result of the unit test case is correct.
=> [Feature] Add support for Ascend devices with nms_rotated

mmcv/ops/bbox.py, mmcv/ops/csrc/common/box_iou_rotated_utils.hpp, mmcv/ops/csrc/pytorch/cpu/bbox_overlaps_cpu.cpp, tests/test_ops/test_bbox.py
Add CPU implementation of ops `bbox_overlaps`
cpu version
pure python version
No
passed `tests/test_ops/test_bbox.py`
**Before PR**:
**After PR**:
=> [CodeCamp #18] add ops bbox_overlaps

mmcv/runner/hooks/evaluation.py
Refine the EvalHook comments
I noticed that according to the implementation of EvalHook, its parameter [start](https://github.com/open-mmlab/mmcv/blob/7e063e3e615153409e7c8b1f67f146905ea392b2/mmcv/runner/hooks/evaluation.py#L88) can also work in iteration mode. However, only the [epoch](https://github.com/open-mmlab/mmcv/blob/7e063e3e615153409e7c8b1f67f146905ea392b2/mmcv/runner/hooks/evaluation.py#L26-L29) mode was stated in the original comment, so I improved the comment.
Improve the comments for [EvalHook](https://github.com/open-mmlab/mmcv/blob/7e063e3e61/mmcv/runner/hooks/evaluation.py).
**Before PR**:
**After PR**:
=> [Docs] Refine the docstring of EvalHook

mmcv/ops/csrc/pytorch/nms_rotated.cpp
Addresses issue https://github.com/open-mmlab/mmcv/issues/2542
For nms_rotated_cuda only adds contiguous call to dets_sorted which is accessed directly. For nms_rotated_cpu the implementation now matches what's in the detectron2 repo.
No, bug fix only.
**Before PR**:
**After PR**:
=> Add missing contiguous calls for nms_rotated

mmcv/ops/csrc/pytorch/mlu/ball_query_mlu.cpp
The motivation of the PR is to fix the tensor descriptor setting in ball_query with MLU backend.
It includes one part:
1. Revise mmcv/ops/csrc/pytorch/mlu/ball_query_mlu.cpp to fix the the setting of tensor descriptor for MLU.
- MLU src code
revise MLU src code of ball_query in directory mmcv/ops/csrc/pytorch/mlu/ball_query_mlu.cpp
If so, please describe how it breaks the compatibility and how the downstream projects …
=> [Fix] Fix tensor descriptor setting in MLU ball_query.

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp, tests/test_ops/test_bbox.py
This PR is for adaptation of the op which name is "bbox_overlaps" on ascend npu device. You can use the op on npu-device by this PR.
=> [Feature]: add bbox_overlaps npu adapter

mmcv/ops/multi_scale_deform_attn.py
The default value for `num_heads` is 8, not 64.
=> [Fix] Fix a typo in the docstring of MSDeformAttn

mmcv/transforms/wrappers.py
Support using Compose in config file, this requirement is common for TTA:
```python
tta_pipeline = [
dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
dict(
type='TestTimeAug',
transforms=[
[
dict(
type='Compose',
transforms=[
dict(type='YOLOv5KeepRatioResize', scale=s),
dict(type='LetterResize', scale=s, allow_scale_up=False, pad_val=dict(img=114))
for s in img_scales
],
)
]
[
dict(type='mmdet.RandomFlip', prob=1.),
dict(type='mmdet.RandomFlip', prob=0.)
],
[
dict(type='mmdet.LoadAnnotations', …
```
=> [Enhancement ] Register compose in TRANSFORMS

mmcv/cnn/bricks/generalized_attention.py
Revise the link of the paper cited by the code.
https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/bricks/generalized_attention.py#L18
(https://arxiv.org/abs/1711.07971) -> (https://arxiv.org/abs/1904.05873)
No.
=> Fix the paper link error in the docstring

mmcv/ops/fused_bias_leakyrelu.py
Add verification for scale, when scale less than 0
**Before PR**:
**After PR**:
=> [Enhance] The argument scale of fused_bias_leakyrelu should be greater than 0

mmcv/ops/csrc/common/mlu/ms_deform_attn_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/ms_deform_attn_mlu.cpp
The motivation of the PR is to improve the performance of ms_deform_attn on Cambricon MLU backend, especially for small channel cases.
MLU src code
Modify MLU src code of ms_deform_attn_mlu_kernel in directory mmcv/ops/csrc/common/mlu/ms_deform_attn_mlu_kernel.mlu.
PyTorch adaptation
Modify ms_deform_attn for PyTorch in mmcv/ops/csrc/pytorch/mlu/ms_deform_attn_mlu.cpp. …
=> [Feature] ms_deform_attn performance optimization

docs/en/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/mlu/mlu_common_helper.h, mmcv/ops/csrc/pytorch/mlu/nms_rotated_mlu.cpp, mmcv/ops/csrc/pytorch/nms_rotated.cpp, mmcv/ops/nms.py, tests/test_ops/test_nms_rotated.py
The motivation of the PR is to support running NmsRotated with Cambricon MLU backend.
- MLU src code
Add MLU src code of NmsRotated in directory mmcv/ops/csrc/pytorch/nms_rotated.cpp.
- PyTorch adaptation
Adapt NmsRotated for PyTorch in mmcv/ops/csrc/pytorch/mlu/nms_rotated_mlu.cpp.
- Unit test
Support test NmsRotated with various backends in tests/test_ops/test_nms_rotated.py. …
=> [Feature] Support NmsRotated with cambricon MLU backend

mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp
Change the value of offset to adapt to the Ascend device.
=> [Fix] Prevent divide-by-zero error on Ascend device for bbox_overlaps

mmcv/ops/csrc/pytorch/cuda/cudabind.cpp, mmcv/ops/csrc/pytorch/cuda/filtered_lrelu.cu
Disable fused_lrelu on gcc < 6
**Before PR**:
**After PR**:
=> [Fix] Skip fused_lrelu op when gcc is less than 6.0 or cuda is less than 10.2

tests/test_ops/test_filtered_lrelu.py
=> [Fix] Skip filtered_lrelu ut when cuda is less than 10.2

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/roi_align_npu.cpp, tests/test_ops/test_roi_align.py
add roi_align op.
add roi_align op.
=> [Feature] Add Ascend support for RoIAlign op

mmcv/ops/bbox.py, setup.py
Fix error for cpu version bbox_overlaps on parrots
=> Fix parrots bbox_overlaps

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/mlu/nms_rotated_mlu.cpp, mmcv/ops/csrc/pytorch/nms_rotated.cpp, mmcv/ops/nms.py, tests/test_ops/test_nms_rotated.py
The motivation of the PR is to support running NmsRotated with Cambricon MLU backend.
- MLU src code
Add MLU src code of NmsRotated in directory mmcv/ops/csrc/pytorch/nms_rotated.cpp.
- PyTorch adaptation
Adapt NmsRotated for PyTorch in mmcv/ops/csrc/pytorch/mlu/nms_rotated_mlu.cpp.
- Unit test
Support test NmsRotated with various backends in tests/test_ops/test_nms_rotated.py. …
=> Support NmsRotated with cambricon MLU backend

mmcv/ops/deform_conv.py, mmcv/ops/modulated_deform_conv.py, tests/test_ops/test_onnx.py
Torch2.0 would parse the forward of autograd.Function, which leads to optimization failed.
1. cast dcn/mdcn shape to int so forward can also be parsed.
2. move onnxruntime inside the test. onnxruntime is optional now.
If this PR introduces a new feature, it is better to list …
=> [Fix] Fix torch2.0 dcn/mdcn symbolic

mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp
1. At present, compared with the bbox_overlaps operator, the iou operator on ascend device has precision error in the fp16 case and does not meet the acceptance standard, so go to the fp32 branch temporarily to avoid the problem.
2. Add support for offset at 0.
3. This change is independent of torch_npu.
=> Modify adaptation of bbox_overlaps op for ascend device

mmcv/ops/csrc/pytorch/cuda/bias_act_cuda.cu, mmcv/ops/csrc/pytorch/cuda/filtered_lrelu.cu, mmcv/ops/csrc/pytorch/cuda/upfirdn2d_kernel.cu, setup.py
build bias_act_cuda on windows will leads to compile error.
disable bias_act_cuda on windows.
TODO: figure out why.
**Before PR**:
**After PR**:
=> [Fix] Replace torch/extension.h with torch/types.h to fix compilation error on Windows

mmcv/ops/conv2d_gradfix.py, tests/test_ops/test_conv_gradfix.py
PyTorch consolidated convolution backward API in [PR](https://github.com/pytorch/pytorch/commit/3dc3651e0ee3623f669c3a2c096408dbc476d122). It means users cannot train styegan2 with PyTorch version higher than 1.10.1
This PR enhances the compatibility of the code referring to the [discussion](https://github.com/pytorch/pytorch/issues/74437)
Resolve [#3](https://github.com/open-mmlab/mmgeneration/issues/322)
Does the modification introduce changes that break the …
=> [Fix] Enhance the compatibility of training stylegan 2

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/box_iou_rotated.py, mmcv/ops/csrc/pytorch/mlu/box_iou_rotated.cpp, tests/test_ops/test_box_iou_rotated.py
The motivation of the PR is to support running BoxIouRotated with Cambricon MLU backend.
modified: docs/en/understand_mmcv/ops.md
modified: docs/zh_cn/understand_mmcv/ops.md
new file: mmcv/ops/csrc/pytorch/mlu/box_iou_rotated.cpp
modified: mmcv/ops/box_iou_rotated.py
modified: tests/test_ops/test_box_iou_rotated.py
If so, please describe how it breaks the compatibility and how the downstream projects should modify their …
=> [Feature] Add the implementation of box_iou_rotated with mlu-ops.

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml, .github/workflows/publish-to-pypi.yml, requirements/docs.txt
=> [Fix] ops can not be built in github action

docs/en/compatibility.md, docs/en/understand_mmcv/ops.md, docs/zh_cn/compatibility.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/active_rotated_filter_npu.cpp, tests/test_ops/test_active_rotated_filter.py
1. This PR is for adaptation of the op which name is "ActiveRotatedFilter" on ascend npu device. You can use the op on npu device by this PR.
2. Fix docs's description: "mmcv.onnex"->"mmcv.onnx", "mim"->"pip".
=> [Feature] Add the support of arf op for ascend device (main)

mmcv/transforms/loading.py
inspired by https://github.com/open-mmlab/mmpretrain/issues/1427
raise error info if imfrombytes fails
run:
```
LoadImageFromFile()(dict(img_path='https://user-images.githubusercontent.com/9102141/87268895-3e0d0780-c4fe-11ea-849e-6140b7e0d4de.gif')
```
**Before PR**:
**After PR**:
=> [Enhance] Raise a error if fails to read image

docs/en/compatibility.md, docs/en/understand_mmcv/ops.md, docs/zh_cn/compatibility.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/active_rotated_filter_npu.cpp, tests/test_ops/test_active_rotated_filter.py
1. This PR is for adaptation of the op which name is "ActiveRotatedFilter" on ascend npu device. You can use the op on npu device by this PR.
2. Fix docs's description: mmcv.onnex->mmcv.onnx.
=> [Feature] Add the support of arf op for ascend device

mmcv/cnn/bricks/conv.py, mmcv/cnn/bricks/norm.py, mmcv/cnn/bricks/padding.py, mmcv/cnn/bricks/plugin.py, mmcv/cnn/bricks/upsample.py, mmcv/ops/nms.py, tests/test_cnn/test_build_layers.py
Make `build_xxx_layer` accept cfg dict with a `class` type
In MMEngine, `build_from_cfg` allows accepting a read `class` type like this:
```python
from mmengine.hooks import LoggerHook
cfg = dict(type=LoggerHook)
hook = build_from_cfg(cfg)
```
However, build_xxx_layer in MMCV does not allow accepting a class type:
```python
from mmcv.cnn import build_conv_layer
from torch.nn import Conv2d
cfg = dict(type=Conv2d, ...)
layer = build_conv_layer(cfg)  # will raise an error
```
This PR makes `build_xxx_layer` can build layer from the …
=> [Enhancement] Make `build_xxx_layer` allow accepting a class type

mmcv/ops/conv2d_gradfix.py, mmcv/ops/corner_pool.py, mmcv/ops/csrc/pytorch/cuda/bias_act_cuda.cu, mmcv/ops/csrc/pytorch/cuda/filtered_lrelu.cu, mmcv/ops/csrc/pytorch/cuda/upfirdn2d_kernel.cu, tests/test_ops/test_filtered_lrelu.py
This PR enables HIP as a backened for pytorch only.
1. conv2d_gradfix.py :Torch version comparison, if the version number has rc or a, there is an error.Conv calls the conversion from cudnn to miopen.
2. corner_pool.py：Torch version comparison, if the version number has rc or a, there is an error.
3. bias_act_cuda.cu/upfirdn2d_kernel.cu : Torch hipify transcoding rule is missing.
4. filtered_lrelu.cu ： cuda : __shfl_xor_sync -> rocm : __shfl_xor
5. test_filtered_lrelu.py ： Test case, add rocm judgment.
Does the modification …
=> [Fix] Fix the support for ROCm

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/mlu/rotated_feature_align_mlu.cpp, tests/test_ops/test_rotated_feature_align.py
Replace the implementation of rotated_feature_align with mlu-ops.
1. modified:   docs/en/understand_mmcv/ops.md
2. modified:   docs/zh_cn/understand_mmcv/ops.md
3. new file:   mmcv/ops/csrc/pytorch/mlu/rotated_feature_align_mlu.cpp
4. modified:  tests/test_ops/test_rotated_feature_align.py
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …
=> [Feature] Add the support for rotated_feature_align with MLU

mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp
It is found that parameter 2(ground truth) of the iou op does not support oversized shape([~32000+, 4]), so add a check.
If the value of gtboxesFP32‘s shape is greater than bboxesFP32, swap them.
=> [Fix] Keep the shape value of ascend iou op's parameter 2 smaller than parameter 1

mmcv/ops/csrc/common/cuda/active_rotated_filter_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cpu/active_rotated_filter.cpp, mmcv/ops/csrc/pytorch/cuda/active_rotated_filter_cuda.cu
1. When num_orientations is not 1, the calculation result of active_rotated_filter op on cpu is inconsistent with that on cuda.
2. Issue link: [2718](https://github.com/open-mmlab/mmcv/issues/2718)，the modified code can pass the sample test.
3. This change does not affect scenarios where num_orientations is 1.
Indexes are added to prevent data from being written to only the first feature map.
**Before PR**:
**After PR**:
=> [Fix] Fix arf op's write conflict when num_orientations is not 1

mmcv/ops/csrc/common/cuda/active_rotated_filter_cuda_kernel.cuh, mmcv/ops/csrc/pytorch/cpu/active_rotated_filter.cpp, mmcv/ops/csrc/pytorch/cuda/active_rotated_filter_cuda.cu
Reverts open-mmlab/mmcv#2822
Sorry, the usage of indices in issue [2718](https://github.com/open-mmlab/mmcv/issues/2718) is wrong, it is not a bug, so revert this pr.
refer to: [mmrote/xx/orconv.py](https://github.com/open-mmlab/mmrotate/blob/main/mmrotate/models/utils/orconv.py).
The value of indices have been added (idx * kH * kW).
=> Revert "[Fix] Fix arf op's write conflict when num_orientations is not 1"

mmcv/transforms/processing.py
I think the index of the second target_scale should be 1 instead of 0 in docstring.
doc correction only.
**Before PR**:
**After PR**:
=> [Docs] small fix for RandomResize doc

requirements/runtime.txt
This commit addresses the bug described in:
https://github.com/open-mmlab/mmcv/issues/2815
Fix an incorrect version constraint on `mmengine`.
Adjust the version constraint to one that is correct.
N/A
N/A
**Before PR**:
**After PR**:
=> Correct mmengine version requirement

mmcv/ops/deform_conv.py, mmcv/ops/modulated_deform_conv.py
Fix deform_conv ops on Ascend NPU.
Fix the problem that the input parameter of padding is incorrect.
Not involving.
We have verified the correctness on related models, such as solov2_r101_dcn_fpn_3x_coco.py.
**Before PR**:
- [ √] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [√ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [√ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [√ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [√ ] …
=> [Fix] Fix deform_conv ops on Ascend NPU

mmcv/cnn/bricks/conv_module.py, tests/test_cnn/test_conv_module.py
Reduce repetitive code for the `fast_conv_bn_eval` feature introduced in https://github.com/open-mmlab/mmcv/pull/2807 .
Create a simple `turn_on_fast_conv_bn_eval` function, and call this function in `__init__` and `create_from_conv_bn`. In the future, `mmengine` might also require this function. See https://github.com/open-mmlab/mmengine/pull/1202 for details.
This PR also subsumes the https://github.com/open-mmlab/mmcv/pull/2836 PR to dynamically bind conv during forward. Test examples added for this case.
It does not break backward-compatibility, as it just introduces a new function.
An existing `ConvModule` object can call `turn_on_fast_conv_bn_eval` to turn on the `fast_conv_bn_eval` feature.
**Before PR**:
**After PR**:
=> [Enhance] Add ConvModule.turn_on_fast_conv_bn_eval to reduce repetitive code and dynamically bind conv during forward

mmcv/ops/csrc/pytorch/bbox_overlaps.cpp, mmcv/ops/csrc/pytorch/nms.cpp, mmcv/ops/csrc/pytorch/roi_align.cpp
support mmcv dipu_mock_cuda=False for ops with cpu fallback
=> [Enhancement] support `dipu_mock_cuda=False` in `dipu` for mmcv ext ops with cpu fallback

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/mlu/diff_iou_rotated_mlu.cpp, mmcv/ops/csrc/pytorch/mlu/mlu_common_helper.h, mmcv/ops/csrc/pytorch/mlu/ms_deform_attn_mlu.cpp, tests/test_ops/test_diff_iou_rotated.py
=> [Feature] Add the implementation of diff_iou_rotated with mlu-ops

docs/zh_cn/get_started/build.md, mmcv/ops/csrc/pytorch/npu/roi_align_npu.cpp
=> [Fix] Fix roi_align npu bug

docs/en/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/points_in_polygons_npu.cpp, mmcv/ops/points_in_polygons.py, tests/test_ops/test_points_in_polygons.py
=> [Feature] Add support of points_in_polyogns for Ascend device

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/box_iou_rotated.py, mmcv/ops/csrc/pytorch/npu/box_iou_rotated_npu.cpp, tests/test_ops/test_box_iou_rotated.py
Add the support of BoxIouRotated op for ascend device
Add the support of BoxIouRotated op for ascend device
**Before PR**:
**After PR**:
Tests
=> [Feature] Add the support of BoxIouRotated op for ascend device

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/__init__.py, mmcv/ops/deform_conv.py, mmcv/ops/modulated_deform_conv.py, tests/test_ops/test_deform_conv.py, tests/test_ops/test_masked_conv2d.py, tests/test_ops/test_modulated_deform_conv.py
support DCN and modulated_DCN op on device mlu
```cpp
modified:   docs/en/understand_mmcv/ops.md: update doc
modified:   docs/zh_cn/understand_mmcv/ops.md: update doc
modified:   mmcv/ops/__init__.py : add class module
modified:   mmcv/ops/deform_conv.py : add class DeformConv2dPack_MLU
modified:   mmcv/ops/modulated_deform_conv.py : add class ModulatedDeformConv2dPack_MLU
modified:   tests/test_ops/test_deform_conv.py : add test to adapt mlu
modified:   tests/test_ops/test_modulated_deform_conv.py : add test to adapt mlu …
```
=> [Feature] Support modulated_deform_conv and deform_conv with cambricon MLU backend

mmcv/cnn/bricks/conv_module.py, tests/test_cnn/test_conv_module.py
The name `fast_conv_bn_eval` is not representative. Rename to `efficient_conv_bn_eval`.
Feature rename.
Code using MMCV 2.0.1 and the `fast_conv_bn_eval` feature will break. However, since this is a new feature, I guess no one used it now.
=> rename fast_conv_bn_eval to efficient_conv_bn_eval

mmcv/cnn/bricks/wrappers.py, tests/test_cnn/test_wrappers.py
`mmcv.cnn.bricks.wrappers` has many forward functions in the form of `if x.numel() == 0 and obsolete_torch_version(TORCH_VERSION, (1, 5))`, where the first condition `x.numel() == 0` would fail `torch.fx`. We can take advantage of shortcut evaluation, by changing the order of condition to `if obsolete_torch_version(TORCH_VERSION, (1, 5)) and x.numel() == 0`. This way, the torch_version compares first, and will not fail `torch.fx` in modern pytorch versions.
Change the order of condition, and add tests for it.
This PR does not break any compatibility.
=> [Enhancement] Change the order of condition to make fx wok

mmcv/ops/csrc/common/cuda/carafe_cuda_kernel.cuh
In preparation for ROCm5.6, this is required for successful compilation. Using AMD's intrinsic resulted in an "ambiguous-type" error. TLDR; some hip-header migration it seems.
This PR will require tests against ROCm5.6 once it is released and the CI is using it.
Using Pytorch's macro to handle the shfl_down intrinsic for functionality and portability.
**Before PR**:
**After PR**:
=> using PyTorch WARP_SHFL_DOWN macro for half support

mmcv/ops/csrc/common/pytorch_npu_helper.hpp, mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp, mmcv/ops/csrc/pytorch/npu/focal_loss_npu.cpp, mmcv/ops/csrc/pytorch/npu/fused_bias_leakyrelu_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_align_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_pool_npu.cpp, mmcv/ops/csrc/pytorch/npu/voxelization_npu.cpp, setup.py
=> Support torch_npu 2.1

mmcv/transforms/utils.py
**fix the bug mentioned in #2926**
**The bug mentioned in #2926 is caused by the data race of multithreading. I do not think it is a good idea to use a pointer here to point to different instances. This can lead to disaster in concurrent situations. To keep modifications minimal, I implemented a version that creates a new copy every time "cache_randomness" is accessed to avoid …
=> [Fix] fix data race risk of `cache_randomness`

mmcv/ops/csrc/pytorch/npu/group_points_npu.cpp, tests/test_ops/test_group_points.py
Add group points forward npu ops in mmcv main branch.
**Before PR**:
**After PR**:
=> [Feature] Add the support for group_points ops with Ascend

mmcv/ops/csrc/common/pytorch_npu_helper.hpp, mmcv/ops/csrc/pytorch/nms_rotated.cpp, mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp, mmcv/ops/csrc/pytorch/npu/focal_loss_npu.cpp, mmcv/ops/csrc/pytorch/npu/fused_bias_leakyrelu_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_align_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_pool_npu.cpp, mmcv/ops/csrc/pytorch/npu/voxelization_npu.cpp, setup.py
=> Support torch_npu v2.1

setup.py, tests/test_ops/test_bbox.py
=> temporarily disable mps ops for torch2.1.0

mmcv/ops/csrc/pytorch/npu/ball_query_npu.cpp, tests/test_ops/test_ball_query.py
Add the support of BallQuery op for Ascend device.
Add operator implementation files and test cases.
Not involving.
Already adapted to original test cases.
**Before PR**:
- [√] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [√] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [√] Bug fixes are covered …
=> [Feature] Add the support of BallQuery op for Ascend device

mmcv/ops/csrc/common/pytorch_npu_helper.hpp, mmcv/ops/csrc/pytorch/npu/focal_loss_npu.cpp
=> Fix torch 1.8 adpater npu bug

mmcv/ops/deform_conv.py
fix deform_conv.py for torch_npu v2.1.
fix deform_conv.py for torch_npu v2.1.
No.
The verification has been performed on the npu device.
**Before PR**:
**After PR**:
=> [Fix] Fix deform_conv.py for torch_npu v2.1

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/rotated_feature_align_npu.cpp, tests/test_ops/test_rotated_feature_align.py
Add NPU operator RotatedFeatureAlign.
Add NPU adaptation to PyTorch code and NPU test cases for this operator.
=> [Feature] Add NPU operator RotatedFeatureAlign

docs/en/understand_mmcv/ops.md, docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/chamfer_distance.py, mmcv/ops/csrc/common/pytorch_npu_helper.hpp, mmcv/ops/csrc/common/pytorch_npu_util.hpp, mmcv/ops/csrc/pytorch/npu/ball_query_npu.cpp, mmcv/ops/csrc/pytorch/npu/chamfer_distance_npu.cpp, mmcv/ops/csrc/pytorch/npu/common_util.h, mmcv/ops/csrc/pytorch/npu/focal_loss_npu.cpp, mmcv/ops/csrc/pytorch/npu/fused_bias_leakyrelu_npu.cpp, mmcv/ops/csrc/pytorch/npu/gather_points_npu.cpp, mmcv/ops/csrc/pytorch/npu/group_points_npu.cpp, mmcv/ops/csrc/pytorch/npu/points_in_polygons_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_align_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_align_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/rotated_feature_align_npu.cpp, mmcv/ops/csrc/pytorch/npu/stack_ball_query_npu.cpp, mmcv/ops/csrc/pytorch/npu/three_interpolate_npu.cpp, setup.py, tests/test_ops/test_ball_query.py, tests/test_ops/test_chamfer_distance.py, tests/test_ops/test_rotated_feature_align.py
=> torch_npu support aclnn and add op

docs/zh_cn/understand_mmcv/ops.md, mmcv/ops/csrc/pytorch/npu/furthest_point_sample_npu.cpp, mmcv/ops/csrc/pytorch/npu/furthest_point_sampling_with_dist_npu.cpp, mmcv/ops/csrc/pytorch/npu/ms_deform_attn_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms3d_normal_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms3d_npu.cpp, mmcv/ops/csrc/pytorch/npu/points_in_box_npu.cpp, mmcv/ops/furthest_point_sample.py, tests/test_ops/test_furthest_point_sample.py, tests/test_ops/test_iou3d.py, tests/test_ops/test_roiaware_pool3d.py
=> add multi npu op

mmcv/ops/csrc/pytorch/npu/nms_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/roipoint_pool3d_forward.cpp, mmcv/ops/nms.py, tests/test_ops/test_roipoint_pool3d.py
=> add npu roipoint_pool3d_forward

mmcv/ops/csrc/common/mlu/ms_deform_attn_fast_mlu_kernel.hpp, mmcv/ops/csrc/common/mlu/ms_deform_attn_fast_mlu_kernel.mlu, mmcv/ops/csrc/pytorch/mlu/ms_deform_attn_mlu.cpp
The motivation of the PR is to add fast kernel for ms_deform_attn_forward with Cambricon MLU backend.
1. Add ms_deform_attn_fast_mlu_kernel.hpp src code.
2. Add ms_deform_attn_fast_mlu_kernel.mlu src code as MLU kernel.
3. Refactor ms_deform_attn_mlu.cpp to support fask kernel with MLU backend for ms_deform_attn_forward.
- MLU src code
Add MLU src code of MsDefromAttnForward with mmcv/ops/csrc/common/mlu/ms_deform_attn_fast_mlu_kernel.hpp and mmcv/ops/csrc/common/mlu/ms_deform_attn_fast_mlu_kernel.mlu
- …
=> [Feature] Support MsDeformAttnForward with fast kernel

mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp, mmcv/ops/csrc/pytorch/npu/common_util.h, mmcv/ops/csrc/pytorch/npu/fused_bias_leakyrelu_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms_npu.cpp, mmcv/ops/csrc/pytorch/npu/nms_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_align_npu.cpp, mmcv/ops/csrc/pytorch/npu/roi_align_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/roipoint_pool3d_forward.cpp
In order to fix some bugs about version 
**Before PR**:
**After PR**:
=> version fix

mmcv/ops/csrc/pytorch/spconv_utils.h
Code should not rely on deprecated APIs as they might get removed in the future
`at::Tensor::type()` method is deprecated and `tensor.scalar_type()` is a recommended way to replace `tensor.type().scalarType()` invocation
**Before PR**:
**After PR**:
=> Do not use deprecated `.type().scalarType()`

mmcv/ops/csrc/pytorch/npu/border_align_npu.cpp
add npu implementation of ops border align
add border_align_npu.cpp file to mmcv\ops\csrc\pytorch\npu
**Before PR**:
**After PR**:
=> add_npu_border_align

mmcv/ops/csrc/pytorch/npu/roiaware_pool3d_npu.cpp
add roiaware_pool3d_npu
add roiaware_pool3d_npu.
**Before PR**:
**After PR**:
=> add roiaware_pool3d_npu

mmcv/ops/csrc/pytorch/npu/box_iou_rotated_npu.cpp, mmcv/ops/csrc/pytorch/npu/boxes_overlap_bev_npu.cpp
=> modify internal calls of npu boxes_overlap_bev & box_iou_rotated

mmcv/ops/box_iou_rotated.py, mmcv/ops/csrc/pytorch/npu/box_iou_rotated_npu.cpp, tests/test_ops/test_iou3d.py
This reverts commit 44d871e7f36bb00afc3946ea36cc6dcf03e07e44.
Change two op call stack in npu.
Revert "adapt boxes_overlap_bev & box_iou_rotated (#3162)".
**Before …
=> Revert "adapt boxes_overlap_bev & box_iou_rotated (#3162)"
